feat: grafana支持 all 选项 --story=115886431
TencentBlueKing/bk-monitor pull request #1043
Opened 2024-01-22 03:01 UTC by tang202388

# Reviewed, transaction id: 2114

2024-01-22 03:16 UTC, tang202388 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            query_config["where"] = remove_all_conditions(query_config["where"])
自测截图：
1、返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/b990bbcd-a723-4331-8439-5f4e6d398cb5)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/eac82039-e026-4d14-8d60-27a9696f1755)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/56cbdcca-2e70-4c56-8fd0-b67ce1181625)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/5d785ed9-e896-4889-a612-9a03da9d56b8)

2、删除__ALL__条件，返回其他条件查询的结果
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/0a8446c9-5ada-41a5-a008-ef4e441020cb)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/dd415b60-f8f5-4c66-b120-8a326a152dae)

2024-01-22 03:19 UTC, tang202388 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            params["promql"] = re.sub(r',\s*}', r'}', params["promql"])
自测截图：
1、返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/843fea35-40e5-488e-b09e-a50258c1677e)

2、删除__ALL__条件，返回其他条件查询的结果
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/041dd68c-6c17-4b59-aa41-e0ece6daa173)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/de97e4a9-860d-431e-bdb5-30667e699704)

![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/f54fac71-76a9-4b60-9de4-55ad9bd1f3f4)

2024-01-29 02:44 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            params["promql"] = re.sub(r',\s*}', r'}', params["promql"])
仪表盘， promql模式下， 支持变量的选择，条件是会被设置成 =~ 或者 =

2024-01-29 02:59 UTC, chenguo367 requested changes

2024-01-29 02:59 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            params["promql"] = re.sub(r"[a-zA-Z_][a-zA-Z0-9_]*=['\"]__ALL__['\"]\s*,?", '', params["promql"])
测试用例:
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip="__ALL__"})
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip='__ALL__'})
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  "__ALL__"  })
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  '__ALL__'  })
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__"})
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =~ "__ALL__" })
avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__" , bk_target_cloude='__ALL__' })

2024-01-29 03:04 UTC, chenguo367 requested changes

2024-01-29 03:04 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/grafana/utils.py
> +    return final_where_list
思考：
```
1. 多个条件的and 和 or连接
ip="__ALL__ " and ip="10.0.0.1"
ip="__ALL__ " or ip="10.0.0.1"
2. 单个条件的肯定与否定逻辑计算
ip="__ALL__ "
ip!="__ALL__ "  # 等于查不出数据（这种情况可以忽略，因为正常不太会这么勇）
# 重点关注第一种情况
```

2024-01-29 08:15 UTC, tang202388 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            params["promql"] = re.sub(r",\s*}", r"}", params["promql"])
自测截图：
1、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip="__ALL__"})    查询返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/b93956f2-616b-4edb-a37d-b773fc2f14e1)
2、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip='__ALL__'})   查询返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/59f1de32-fb80-4768-9f48-12c7985267aa)
3、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  "__ALL__"  })  查询返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/b0a6252c-75bd-44cc-8583-c19789679ebd)
4、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  '__ALL__'  })  查询返回所有数据
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/d0c523d8-f9f9-4cad-8c93-0aace38caecb)
5、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__"})  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/3b504ef1-df9f-4abb-aad6-320b4d7666d2)
6、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =~ "__ALL__" })   查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/2509b03f-ff80-4bc5-b9f6-08fe964b9333)
7、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__" , bk_target_cloude='__ALL__' })   查询返回所
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/0c6e00c2-ced1-44a4-b517-767eb821e1f8)
8、avg by (bk_target_ip) (avg_over_time(bkmonitor:system:load:load1{bk_target_ip="*.*.*.*",bk_target_ip="__ALL__"}[1m]))  查询返回 bk_target_ip="*.*.*.*"的值
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/e7116d36-11bb-4ee0-9b2b-c9c821d9eb93)

2024-01-29 08:30 UTC, tang202388 commented on bkmonitor/packages/monitor_web/grafana/resources/unify_query.py
> +            params["promql"] = re.sub(r",\s*}", r"}", params["promql"])
1、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip="__ALL__"})  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/5fbe24bf-e362-4431-a8f9-49d98348d7c4)
2、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip='__ALL__'})  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/3b44a8d6-2a82-47a1-95af-c43cd4dddad1)
3、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  "__ALL__"  })  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/4c7d92c6-5906-4a2d-9b23-af05b6804ac8)
4、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =  '__ALL__'  })   查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/863576e0-bf72-4ec3-baca-6063d55b3337)
5、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__"})   查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/102fc98e-34b7-4c60-8611-db228635e0ca)
6、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip =~ "__ALL__" })  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/daf2a9d7-8dbd-4d76-94ae-2be4dc8096e7)
7、avg by (bk_target_ip) (bkmonitor:system:disk:in_use{bk_target_ip=~"__ALL__" , bk_target_cloude='__ALL__' })  查询返回所有
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/854c9fb5-0dbf-4cb8-909d-03cb8743dd22)
8、avg by (bk_target_ip) (avg_over_time(bkmonitor:system:load:load1{bk_target_ip="*.*.*.*",bk_target_ip="__ALL__"}[1m]))  查询返回 bk_target_ip="*.*.*.*"的值
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/b90470d0-9b6d-42d2-a75f-eeb22e33ccdf)

2024-03-01 03:42 UTC, unique0lai commented
考虑到使用场景的特殊性，只有在特定条件下触发该机制
1. promql的情况下，当method为~=或=，value为__ALL__时，剔除该条件
2. 结构化参数查询的情况下，当method为肯定条件(eq/include/regex)时，剔除该条件，如果剔除该条件导致逻辑恒等，则消除其他条件。

2024-03-11 03:43 UTC, unique0lai approved these changes, later dismissed

2024-03-11 03:58 UTC, chenguo367 approved these changes

2024-03-11 03:59 UTC, merged