feature: 增加DeepFlow数据源发现、grafana自动接入
TencentBlueKing/bk-monitor pull request #130
Opened 2023-11-08 06:52 UTC by rxwycdh

2023-11-08 09:39 UTC, liuwenping requested changes

2023-11-08 09:39 UTC, liuwenping commented on .pre-commit-config.yaml
> +    rev: 5.12.0
这个和PR无关的内容，先不放这里提交

2023-11-08 09:39 UTC, liuwenping commented on bkmonitor/apm/management/commands/pre_calculate.py
> +        TODO 支持指定队列
这个注释没看懂

2023-11-08 09:39 UTC, liuwenping commented on bkmonitor/apm_ebpf/handlers/deepflow.py
> +            services = WorkloadHandler.list_services(self.bk_biz_id, DeepflowComp.NAMESPACE, cluster_id)
这里应该可以直接获取到nodeTargeIP，不需要后面再list_node一次

2023-11-08 10:12 UTC, liuwenping requested changes

2023-11-08 10:12 UTC, liuwenping commented on bkmonitor/packages/monitor_web/grafana/dashboards/apm-ebpf-Application-Cloud-Host-Map.json
这些文件都放到一个子目录下吧。

2023-11-09 12:21 UTC, liuwenping requested changes

2023-11-09 12:21 UTC, liuwenping commented on bkmonitor/packages/monitor_web/grafana/provisioning.py
> +        templates = [n for n in os.listdir(path) if fnmatch.fnmatch(n, "apm-ebpf-*.json")]
把要默认import的文件名字，直接写在这里吧。就不用fnmatch来搜索一下

2023-11-09 12:21 UTC, liuwenping commented on bkmonitor/apm/core/discover/precalculation/daemon.py
> +        logger.info(f"trigger successfully, send dataId: {data_id}, queue: {queue_name}, params: {params}")
去掉和PR无关的改动内容

2023-11-09 12:37 UTC, unique0lai approved these changes

2023-11-09 12:37 UTC, merged