perf: query_topo_instance interface perf
TencentBlueKing/bk-monitor pull request #1355
Opened 2024-03-12 09:40 UTC by redyfang

2024-03-15 02:28 UTC, liuwenping requested changes

2024-03-15 02:28 UTC, liuwenping commented on bkmonitor/apm/core/handlers/instance_handlers.py
> +            return ujson.loads(json_res)
全局已经patch，这里不需要替换

2024-03-15 03:01 UTC, liuwenping requested changes

2024-03-15 03:01 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +        fields = serializers.ListField(label="系列化字段", required=False, default=[])
没有看到请求这个topo instance接口的地方的修改，应该要增加传递fields字段的参数吧

2024-03-15 03:01 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +        params = [(data[i:i + self.BATCH_SIZE], fields) for i in range(0, len(data), self.BATCH_SIZE)]
这个改为线程池的做法，需要验证一下实际的优化性能，贴一下实际提升的数据

2024-03-20 02:06 UTC, redyfang commented on bkmonitor/apm/core/handlers/instance_handlers.py
> +            return ujson.loads(json_res)
已去掉

2024-03-20 02:06 UTC, redyfang commented on bkmonitor/apm/resources.py
> +        fields = serializers.ListField(label="系列化字段", required=False, default=[])
topo_view 已添加

2024-03-20 02:06 UTC, redyfang commented on bkmonitor/apm/resources.py
> +        params = [(data[i:i + self.BATCH_SIZE], fields) for i in range(0, len(data), self.BATCH_SIZE)]
已去掉

2024-03-20 02:16 UTC, liuwenping requested changes

2024-03-20 02:16 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +                res = self.handle_pagination(data=data, params=validated_request_data)
这里的res为啥不需要序列化了。是不是需要回到最开始的逻辑通过`TopoInstanceSerializer`来序列化一遍

2024-03-20 02:18 UTC, redyfang commented on bkmonitor/apm/resources.py
> +                res = self.handle_pagination(data=data, params=validated_request_data)
res = list(page_data.values(*fields))  这个已经系列化

2024-03-20 02:19 UTC, redyfang commented on bkmonitor/apm/resources.py
> +                res = self.handle_pagination(data=data, params=validated_request_data)
res = self.handle_pagination(data=data, params=validated_request_data)  这里的 data 在 上面进行 fields 判断时系列化

2024-03-26 06:50 UTC, liuwenping approved these changes

2024-03-26 06:50 UTC, merged