feat: 存量实时监控策略切换 --story=116292554
TencentBlueKing/bk-monitor pull request #1501
Opened 2024-03-28 08:58 UTC by tang202388

2024-03-28 09:21 UTC, tang202388 commented
自测截图：
1.1   迁移前 QueryConfigModel 和 ItemModel 涉及字段内容
(1) QueryConfigModel  的 metric_id 字段内容：custom.2_bkmonitor_time_series_1573157.__default__.in_use
(2)  QueryConfigModel  的 data_source_label 字段内容：custom
(3) QueryConfigModel  的 config 字段内容：
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/3d99822d-8280-4515-b116-331e8fb78b16)
(4) ItemModel 的 origin_sql 字段的内容为空
1.2    迁移后QueryConfigModel 和 ItemModel 涉及字段内容
(1) QueryConfigModel  的 metric_id 字段内容：data_label_1:in_use
(2)  QueryConfigModel  的 data_source_label 字段内容：prometheus
(3) QueryConfigModel  的 config 字段内容：
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/1fd5785d-be2b-4f38-9001-91f24052908d)
(4) ItemModel 的 origin_sql 字段的内容：data_label_1:in_use >= 20{bk_target_ip=~"^(10.0.1.1)|(10.0.1.2)|(10.0.1.3)$"} or data_label_1:in_use >= 20{bk_target_cloud_id!~"^(222)$"}

2.1  迁移前 QueryConfigModel 和 ItemModel 涉及字段内容
(1) QueryConfigModel  的 metric_id 字段内容：custom.2_bkmonitor_time_series_1573157.__default__.in_use
(2)  QueryConfigModel  的 data_source_label 字段内容：custom
(3) QueryConfigModel  的 config 字段内容：
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/28640574-bfc2-48e2-b09b-4a285f5d284e)
(4) ItemModel 的 origin_sql 字段的内容为空
2.2  迁移后QueryConfigModel 和 ItemModel 涉及字段内容
(1) QueryConfigModel  的 metric_id 字段内容：data_label_1:in_use
(2)  QueryConfigModel  的 data_source_label 字段内容：prometheus
(3) QueryConfigModel  的 config 字段内容：
![image](https://github.com/TencentBlueKing/bk-monitor/assets/141982444/b4f36ab3-2b2e-4f44-ac33-6c9bc8c4d531)
(4) ItemModel 的 origin_sql 字段的内容：data_label_1:in_use >= 20{bk_target_ip=~"(10.0.1.1)|(10.0.1.2)|(10.0.1.3)", bk_target_cloud_id!~"(222)"}

2024-04-10 04:06 UTC, chenguo367 commented
> 自测截图： 1.1 迁移前 QueryConfigModel 和 ItemModel 涉及字段内容 (1) QueryConfigModel 的 metric_id 字段内容：custom.2_bkmonitor_time_series_1573157.**default**.in_use (2) QueryConfigModel 的 data_source_label 字段内容：custom (3) QueryConfigModel 的 config 字段内容： ![image](https://private-user-images.githubusercontent.com/141982444/317666192-3d99822d-8280-4515-b116-331e8fb78b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjIxNDEsIm5iZiI6MTcxMjcyMTg0MSwicGF0aCI6Ii8xNDE5ODI0NDQvMzE3NjY2MTkyLTNkOTk4MjJkLTgyODAtNDUxNS1iMTE2LTMzMWU4ZmI3OGIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNDA0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTAzOTViZTJkMWU2MjM0ZDdiNGZjYTI3OGYyMDgxZjcwMDBmZjE1NDcxMmFkYjVlMGFhOGVlMmE3MzQxNjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZJdIg0gmRxpTrNvvTNSP9jk52aPk3DTeZn6EQOMNOoo) (4) ItemModel 的 origin_sql 字段的内容为空 1.2 迁移后QueryConfigModel 和 ItemModel 涉及字段内容 (1) QueryConfigModel 的 metric_id 字段内容：data_label_1:in_use (2) QueryConfigModel 的 data_source_label 字段内容：prometheus (3) QueryConfigModel 的 config 字段内容： ![image](https://private-user-images.githubusercontent.com/141982444/317666555-1fd5785d-be2b-4f38-9001-91f24052908d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjIxNDEsIm5iZiI6MTcxMjcyMTg0MSwicGF0aCI6Ii8xNDE5ODI0NDQvMzE3NjY2NTU1LTFmZDU3ODVkLWJlMmItNGYzOC05MDAxLTkxZjI0MDUyOTA4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNDA0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTQ2N2EyNzE1MzlkM2ZhOTkwOGMzNjQyYjBjYzAwYmY0YWRjNDYxY2Q2OWVhMjQzYmExMDBkYjZhNTAwNWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L6xyN-pUabnZY1EPJylyR-r3QoUH2nLUGmSU-Zl5a90) (4) ItemModel 的 origin_sql 字段的内容：data_label_1:in_use >= 20{bk_target_ip=~"^(10.0.1.1)|(10.0.1.2)|(10.0.1.3)$"} or data_label_1:in_use >= 20{bk_target_cloud_id!~"^(222)$"}
> 
> 2.1 迁移前 QueryConfigModel 和 ItemModel 涉及字段内容 (1) QueryConfigModel 的 metric_id 字段内容：custom.2_bkmonitor_time_series_1573157.**default**.in_use (2) QueryConfigModel 的 data_source_label 字段内容：custom (3) QueryConfigModel 的 config 字段内容： ![image](https://private-user-images.githubusercontent.com/141982444/317667190-28640574-bfc2-48e2-b09b-4a285f5d284e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjIxNDEsIm5iZiI6MTcxMjcyMTg0MSwicGF0aCI6Ii8xNDE5ODI0NDQvMzE3NjY3MTkwLTI4NjQwNTc0LWJmYzItNDhlMi1iMDliLTRhMjg1ZjVkMjg0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNDA0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDhmNzNjMzAyZWZmYjU0NDI3MjdlMjY0Mzg2NTk4NWNlYmYzZjhhY2YwZTI3NDJhMjljNzI3ZTg4ZmI0NTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sdgDvunPv8D8qF7ACUa0wE_2XyHLCoZdBLuyupj8lGk) (4) ItemModel 的 origin_sql 字段的内容为空 2.2 迁移后QueryConfigModel 和 ItemModel 涉及字段内容 (1) QueryConfigModel 的 metric_id 字段内容：data_label_1:in_use (2) QueryConfigModel 的 data_source_label 字段内容：prometheus (3) QueryConfigModel 的 config 字段内容： ![image](https://private-user-images.githubusercontent.com/141982444/317667713-b4f36ab3-2b2e-4f44-ac33-6c9bc8c4d531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjIxNDEsIm5iZiI6MTcxMjcyMTg0MSwicGF0aCI6Ii8xNDE5ODI0NDQvMzE3NjY3NzEzLWI0ZjM2YWIzLTJiMmUtNGY0NC1hYzMzLTZjOWJjOGM0ZDUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNDA0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjVhMTIwYThhZTE4ZWEyNzNhMzg2MmY0ZGNhNTFmMzNkZjI3NDBjMWFjY2QxNDBmNzVjMjAzYmUxOTZiNzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ULP20prCZHUSODjz3AuJJbve2CKpwYIxdsLKwG6ZcC8) (4) ItemModel 的 origin_sql 字段的内容：data_label_1:in_use >= 20{bk_target_ip=~"(10.0.1.1)|(10.0.1.2)|(10.0.1.3)", bk_target_cloud_id!~"(222)"}

这里带表达式和条件的转换需要换一个顺序：

data_label_1:in_use >= 20{bk_target_ip=~"(10.0.1.1)|(10.0.1.2)|(10.0.1.3)", bk_target_cloud_id!~"(222)"}
应该是: 
data_label_1:in_use{bk_target_ip=~"(10.0.1.1)|(10.0.1.2)|(10.0.1.3)", bk_target_cloud_id!~"(222)"} >= 20

2024-04-10 04:08 UTC, chenguo367 requested changes

2024-04-10 04:08 UTC, chenguo367 commented on bkmonitor/bkmonitor/migrations/0159_migrate_real_time_strategy.py
> +logger = logging.getLogger("bkmonitor")
migration文件，直接用print 即可

2024-04-10 04:08 UTC, chenguo367 commented on bkmonitor/bkmonitor/migrations/0159_migrate_real_time_strategy.py
> +    try:
异常捕获太大范围了。
这里需要按query_config来处理。
当前逻辑是循环处理query_configs， 其中一个配置异常，不应该影响后续的配置处理。

2024-04-10 04:08 UTC, chenguo367 commented on bkmonitor/bkmonitor/migrations/0159_migrate_real_time_strategy.py
> +                    migrated_items.append(item)
运行到这里表示成功处理了配置，待后续更新
print(f"[done]  process strategy {strategy_id}")
如果异常，同样记录
print(f"[X]  process strategy {strategy_id} error: {exec}")

2024-04-10 04:08 UTC, chenguo367 commented on bkmonitor/bkmonitor/migrations/0159_migrate_real_time_strategy.py
> +                promql = conditions_to_promql(promql, agg_condition)
顺序反了， 先转换过滤条件，再转换表达式。
```
# 正确的promql如下：
data_label_1:in_use{bk_target_ip=~"(10.0.1.1)|(10.0.1.2)|(10.0.1.3)", bk_target_cloud_id!~"(222)"} >= 20
```

2024-04-26 10:04 UTC, chenguo367 approved these changes

2024-04-26 10:04 UTC, merged