perf: [apm] profile services interface perf  --bug=122870488
TencentBlueKing/bk-monitor pull request #1608
Opened 2024-04-12 10:10 UTC by redyfang

2024-05-06 01:55 UTC, liuwenping approved these changes, later dismissed

2024-05-06 01:55 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/resources.py
> +        service_map = self.batch_query_profile_services_detail(applications)
有可能通过修改接口的方式，批量获取服务么？ 批量查接口，感觉不是很合适

2024-05-07 03:05 UTC, redyfang commented on bkmonitor/packages/apm_web/profile/resources.py
> +        service_map = self.batch_query_profile_services_detail(applications)
可以修改接口来实现，在 query_profile_services_detail 这个接口中作兼容。或者新开一个批量查询接口，处理上可能麻烦一点，需要转化查询条件 bk_biz_id in [] and app_name in [] 的方式来查询，然后就是数据处理了

2024-05-09 07:06 UTC, liuwenping requested changes

2024-05-09 07:06 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +        bk_biz_id = serializers.IntegerField(required=False)
业务ID需要保留，强制需要传。 不允许跨业务查询

2024-05-09 07:12 UTC, redyfang commented on bkmonitor/apm/resources.py
> +        bk_biz_id = serializers.IntegerField(required=False)
已调整

2024-05-09 09:02 UTC, liuwenping approved these changes

2024-05-09 09:02 UTC, merged