perf: [apm] list_application interface perf  --bug=122870610
TencentBlueKing/bk-monitor pull request #1609
Opened 2024-04-12 10:19 UTC by redyfang

2024-05-09 07:06 UTC, liuwenping requested changes

2024-05-09 07:06 UTC, liuwenping commented on bkmonitor/bkmonitor/iam/drf.py
> +from concurrent.futures import ThreadPoolExecutor, as_completed
`from concurrent.futures import ThreadPoolExecutor`
这个方式的线程池，上下文没有带入到线程中，会导致在线程中拿不到request相关信息

2024-05-14 06:13 UTC, redyfang commented on bkmonitor/bkmonitor/iam/drf.py
> +from concurrent.futures import ThreadPoolExecutor, as_completed
已调整，已使用 bkmonitor.utils.thread_backend.ThreadPool 线程池

2024-06-04 03:32 UTC, liuwenping approved these changes, later dismissed

2024-06-04 03:55 UTC, liuwenping approved these changes

2024-06-04 03:55 UTC, merged