feat: 新增api调用异常指标上报 --story=116964176
TencentBlueKing/bk-monitor pull request #1626
Opened 2024-04-16 06:43 UTC by EASYGOING45

2024-04-16 12:33 UTC, chenguo367 requested changes

2024-04-16 12:33 UTC, chenguo367 commented on bkmonitor/core/drf_resource/exceptions.py
> +        metrics.API_FAILED_REQUESTS_TOTAL.labels(
这个指标设计：记录调用第三方系统api失败的数据，不是记录自身服务的异常数据。
监控所有的api调用，都通过APIResource， 所以需要再APIResource逻辑里进行统计指标。

2024-04-18 07:22 UTC, chenguo367 requested changes

2024-04-18 07:22 UTC, chenguo367 commented on bkmonitor/core/drf_resource/contrib/api.py
> +            logger.exception(_lazy("【模块：{}】请求APIGW错误：{}，请求url: {} ".format(self.module_name, err, request_url)))
日志 不需要进行国际化。国际化后的日志反而会引起基于关键字查询日志定位的难度。

2024-04-18 07:22 UTC, chenguo367 commented on bkmonitor/core/prometheus/metrics.py
> +API_FAILED_REQUESTS_TOTAL = Counter(
指标统计待实现

2024-04-22 03:26 UTC, chenguo367 requested changes

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/bcs_storage/default.py
> -        headers = {"Authorization": f"Bearer {settings.BCS_API_GATEWAY_TOKEN}"}
headers 漏处理了

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/bkchat/default.py
> +            self.report_api_failure_metric(error_code=getattr(e, 'code', 0), exception_type=BKAPIError.__name__)
记录异常逻辑， 在上面`            super(SendNoticeGroupMsg, self).perform_request(validated_request_data)`语句中应该已经有了，这里是否有重复记录？

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/cmdb/client.py
>          except NoRelatedResourceError:
except NoRelatedResourceError as exec:
        # 下面直接引用exec对象的属性。不用类名，因为NoRelatedResourceError 可以被继承成新异常。 这里捕获的时候，exec可能是NoRelatedResourceError的子类（虽然没有集成这个类的，但代码需要考虑）

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/cmsi/default.py
> +            self.report_api_failure_metric(error_code=BKAPIError.code, exception_type=BKAPIError.__name__)
BKAPIError 在基类已经统计过， 然后才raise的， 这里再统计，就重复了。

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/common/default.py
> +            self.report_api_failure_metric(error_code=getattr(api_error, 'code', 0), exception_type=BKAPIError.__name__)
重复统计

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/devops/default.py
> +            self.report_api_failure_metric(error_code=BKAPIError.code, exception_type=BKAPIError.__name__)
这里使用一个新的异常类来表达蓝盾环境未部署这个异常。

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/devops/default.py
> -        return super(ListUserProjectResource, self).perform_request(validated_request_data)
这里看起来删错了吧？实际实现没了

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/job/default.py
> +                    error_code=APIPermissionDeniedError.code, exception_type=APIPermissionDeniedError.__name__
引用异常对象的属性。  error.code

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/api/sops/default.py
> +                self.report_api_failure_metric(error_code=code, exception_type=BKAPIError.__name__)
重复统计

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/bkmonitor/utils/bcs.py
> +        return {"Authorization": f"Bearer {settings.BCS_API_GATEWAY_TOKEN}"}
这里建议还是super一下。 直接重写实现， 后面蓝鲸apigateway 调用标准化改造，可能会漏掉这里。

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/bkmonitor/utils/bcs.py
> +        return {"Authorization": f"Bearer {settings.BCS_API_GATEWAY_TOKEN}"}
多一些字段没太大问题

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/core/drf_resource/contrib/api.py
> +        except Exception as error:  # pylint: disable=broad-except
这里不用捕获了， 除了超时外， 剩下的http抛出的异常，属于底层异常（如网络等问题） 这类异常不需要再次逻辑处理。 基础环境问题直接抛出即可。

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/core/drf_resource/contrib/api.py
> +        except Exception as error:  # pylint: disable=broad-except
我们的api逻辑处理起点：收到第三方服务的响应后

2024-04-22 03:26 UTC, chenguo367 commented on bkmonitor/core/drf_resource/contrib/api.py
> +            user_name=getattr(self, 'bk_username', 'Unknown user'),
默认值用空字符串

2024-04-22 06:29 UTC, EASYGOING45 commented on bkmonitor/api/cmdb/client.py
>          except NoRelatedResourceError:
好的，这部分感觉在上方的super()中会被上报一次，应该存在重复上报问题哈～

2024-04-22 06:42 UTC, EASYGOING45 commented on bkmonitor/api/devops/default.py
> -        return super(ListUserProjectResource, self).perform_request(validated_request_data)
这里是这样的，调试过程中，发现请求会先走request()方法，这里原先的逻辑是如果settings.BK_CI_HOST不存在，则返回[]，这里直接重写request()方法进行判断和提前返回，结果和功能和之前的代码是一样的哈～

2024-04-22 06:47 UTC, EASYGOING45 commented on bkmonitor/core/drf_resource/contrib/api.py
> +        except Exception as error:  # pylint: disable=broad-except
好的，之前的理解是需要捕获所有类型和所有原因的异常，目前更正为不捕获除超时外的底层环境异常～

2024-04-22 07:03 UTC, EASYGOING45 commented on bkmonitor/api/devops/default.py
> +            self.report_api_failure_metric(error_code=BKAPIError.code, exception_type=BKAPIError.__name__)
好的，请问这里的错误码定为多少呀～

2024-04-22 07:25 UTC, chenguo367 commented on bkmonitor/api/devops/default.py
> +            self.report_api_failure_metric(error_code=BKAPIError.code, exception_type=BKAPIError.__name__)
bkmonitor/core/errors/api.py
向后累加即可 。

2024-04-22 07:27 UTC, EASYGOING45 commented on bkmonitor/api/devops/default.py
> +            self.report_api_failure_metric(error_code=BKAPIError.code, exception_type=BKAPIError.__name__)
好的，此处已更改～

2024-04-22 11:44 UTC, chenguo367 approved these changes

2024-04-22 12:16 UTC, chenguo367 approved these changes

2024-04-22 13:01 UTC, merged