feat: 链路健康内置策略，在采集删除后，需要同步删除对应策略和分派规则 --story=116629395
TencentBlueKing/bk-monitor pull request #1627
Opened 2024-04-16 06:52 UTC by lthon-sha

2024-04-16 06:57 UTC, lthon-sha commented on bkmonitor/packages/monitor_web/strategies/user_groups.py
> +    groups.delete()
如果这个用户组被编辑，或者被用于其他策略，会造成问题。

2024-04-18 10:03 UTC, chenguo367 requested changes

2024-04-18 10:03 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/collecting/resources/backend_resources.py
> +        configs_not_exist = not CollectConfigMeta.objects.filter(bk_biz_id=bk_biz_id, create_user=username).exists()
变量命名不要用 not xxx，后续不好维护和理解。

```
# 使用更具描述性的变量名  by GPT
configs_exist = CollectConfigMeta.objects.filter(bk_biz_id=bk_biz_id, create_user=username).exists()
```

2024-04-18 10:03 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/collecting/resources/backend_resources.py
> +        configs_not_exist = not CollectConfigMeta.objects.filter(bk_biz_id=bk_biz_id, create_user=username).exists()
loader.delete(remove_user_from_group=not configs_exist)

2024-04-18 10:03 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/loader/datalink_loader.py
> +        manager = RuleGroupManager(self.bk_biz_id)
```
采集和内置策略的对应关系：
# 默认内置2条策略，覆盖全部采集配置
采集配置 -> 策略 （N to 2)
# 基于采集id进行分派， 一个采集对应2条分派规则
采集配置 -> 分派规则 （1 to 2)

分派规则 -> 用户组 (N to 1)
用户组 -> 用户  (1 to N)
```

2024-04-18 10:03 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/loader/datalink_loader.py
> +        manager = RuleGroupManager(self.bk_biz_id)
基于上面的对应关系。
当采集配置删除后， 
需要跟进删除的模型为： 
- 分派规则
- 策略， 用户组不需要删除
- 用户组内的用户， 当此次删除的人员没有另外的采集配置时，用户组清理该用户。

2024-04-18 10:22 UTC, lthon-sha commented
规则组需要删除吗？每个业务下的所有采集配置会共用一个规则组，如果把全部规则删除了，规则组要不要删除。

2024-04-18 10:22 UTC, lthon-sha commented on bkmonitor/packages/monitor_web/strategies/loader/datalink_loader.py
> +        manager = RuleGroupManager(self.bk_biz_id)
规则组需要删除吗？每个业务下的所有采集配置会共用一个规则组，如果把全部规则删除了，规则组要不要删除。

2024-04-22 09:56 UTC, chenguo367 approved these changes

2024-04-22 09:56 UTC, merged