feat: 【APM】新建 APM 应用需要补充一条默认 QPS 配置记录  --bug=123357047
TencentBlueKing/bk-monitor pull request #1804
Opened 2024-05-11 07:07 UTC by redyfang

2024-05-13 08:17 UTC, liuwenping requested changes

2024-05-13 08:17 UTC, liuwenping commented on bkmonitor/packages/apm_web/models/application.py
> +        res["qps"] = settings.APM_APP_QPS
这里需要从DB从获取，应该不是直接给定一个数值

2024-05-14 02:07 UTC, redyfang commented on bkmonitor/packages/apm_web/models/application.py
> +        res["qps"] = settings.APM_APP_QPS
在 web 侧，想要从 DB 中获取， qps 配置，就必须在  ApmMetaConfig 增加配置才行
这个地方主要 在新建应用时，传一个 qps 配置 到API 侧

2024-05-15 14:39 UTC, liuwenping commented on bkmonitor/packages/apm_web/models/application.py
> +        res["qps"] = settings.APM_APP_QPS
从参数层面来处理，如果是web侧发起的，可以从接口上预留一个参数给到页面传过来，当前没有的话，就给一个默认值

2024-05-17 02:58 UTC, redyfang commented on bkmonitor/packages/apm_web/models/application.py
> +        res["qps"] = settings.APM_APP_QPS
已处理，暂时不考虑编辑修改

2024-05-19 14:51 UTC, liuwenping approved these changes

2024-05-19 14:51 UTC, merged