feat: 拨测任务下发配置文件， 新增拨测组id的维度注入 --story=118495753
TencentBlueKing/bk-monitor pull request #2403
Opened 2024-07-24 09:26 UTC by tang202388

# Reviewed, transaction id: 13001

2024-09-06 03:49 UTC, chenguo367 requested changes

2024-09-06 03:49 UTC, chenguo367 commented on bkmonitor/packages/monitor/models/models.py
> +            raise CustomException(_("不存在的任务id:%s") % pk)
任务组id 不是必须路径， 拿不到不影响拨测下发。 因此这里不要raise。
task_group_id 给个默认值 "0" 就好

2024-09-06 03:49 UTC, chenguo367 commented on bkmonitor/packages/monitor/models/models.py
> +                labels["$body"]["node_id"] = (
1. 给出改动前后， ICMP的下发 参数 params 的对比
2. 给出非ICMP的task的改动前后下发参数 params的对比

2024-09-11 08:07 UTC, tang202388 commented on bkmonitor/packages/monitor/models/models.py
> +                labels["$body"]["node_id"] = (
自测截图：
1、修改前
1.1 修改前ICMP的下发参数 params
![image](https://github.com/user-attachments/assets/886f5389-8d63-4dca-884e-8620ed83c955)
1.2 修改前非ICMP的下发参数 params
![image](https://github.com/user-attachments/assets/bca04151-a581-422f-b397-e1064a059ed7)
2、修改后
2.1 修改后ICMP的下发参数 params
![image](https://github.com/user-attachments/assets/2b71136c-6a78-4974-94c9-eec14c70f765)
与修改前对比多了以下部分
![image](https://github.com/user-attachments/assets/655636df-0125-4202-bb3d-a5a34ad8eb71)
2.2 修改后非ICMP的下发参数 params
![image](https://github.com/user-attachments/assets/a80ec33e-5a0c-4a71-90c5-9d69b3a427cb)
与修改前对比多了以下部分
![image](https://github.com/user-attachments/assets/8cc92313-c4bb-4506-ac18-15bbccff3035)

2024-09-12 06:17 UTC, chenguo367 commented on bkmonitor/packages/monitor/models/models.py
> +                labels["$body"]["node_id"] = (
LGTM

2024-09-12 06:17 UTC, merged