feat: 【产品功能】告警策略列表筛选功能字段自定义显示 --story=118568821
TencentBlueKing/bk-monitor pull request #2475
Opened 2024-08-05 09:00 UTC by tang202388

2024-08-05 09:08 UTC, tang202388 commented
自测截图：
1. 可以正常返回新增的筛选种类(告警级别、算法类型、失效类型)的统计数据
![image](https://github.com/user-attachments/assets/f8cb7feb-08ac-4bf9-ad90-51e240aeafe9)
2. 新增筛选种类(告警级别、算法类型、失效类型)之前已支持过滤搜索
![image](https://github.com/user-attachments/assets/cab16117-d89f-4bdd-b1d7-47c23f76ed78)
![image](https://github.com/user-attachments/assets/ba980b0c-c90c-4950-a824-2bf3d31a71ea)
![image](https://github.com/user-attachments/assets/a5b245b8-ac6d-42e3-8428-94933b9a167b)

2024-08-07 02:27 UTC, chenguo367 requested changes

2024-08-07 02:27 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +        all_algorithm_type = {
可以考虑直接复用 AlgorithmModel.ALGORITHM_CHOICES
这里貌似还漏了2个ai算法
<img width="709" alt="image" src="https://github.com/user-attachments/assets/75c0ad02-d49f-49a5-9709-f3127580a270">

2024-08-07 02:27 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +        all_invalid_type = {
也建议用StrategyModel.InvalidType.Choices
后续有增删能够同步

2024-08-07 03:02 UTC, merged