feat: APM ES 查询切换至 datasource 模块 --story=118979611
TencentBlueKing/bk-monitor pull request #2583
Opened 2024-08-16 08:08 UTC by ZhuoZhuoCrayon

2024-08-27 11:56 UTC, liuwenping commented on bkmonitor/metadata/models/result_table.py
> +            table_id = query_table_id.replace("apm_global_", "apm_global.", 1)
在metadata模块直接写这个逻辑，不太合适
另外这个表名，前缀是由用户配置的，不一定是这个名字

2024-08-27 11:56 UTC, liuwenping commented on bkmonitor/metadata/models/storage.py
> +            index_info_map: Dict[str, Dict[str, Any]] = getdata(func(index=self.search_format_v2(), **extra))
bug: 这里应该调用 `v1` 而不是 `v2` 的方法

2024-08-27 11:56 UTC, liuwenping commented on bkmonitor/metadata/utils/es_tools.py
> +    if username and password:
bug: 这个写法不对，如果配置里pass是一个空字符串，这里就不会增加http_auth了

2024-08-31 03:01 UTC, liuwenping requested changes

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/query_api/resources.py
> +            required=False, label="索引全名列表（不为空优先使用", child=serializers.CharField(required=True, label="索引名")
label 是不是少了一边括号

另外这个`full_index_names`，有点模糊，实际上还是不知道什么是全名，要精确到具体的物理索引么？
直接叫`index_names`是不是更好，然后再注释写几个例子放这里，这样一眼就明白了

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/metadata/utils/es_tools.py
> +        "use_ssl": datasource_info["is_ssl_verify"],
`is_ssl_verify`这个参数的获取，建议使用get，然后给一个默认值 `False`，应该是可选参数

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/metadata/utils/es_tools.py
> +    password = datasource_info["auth_info"]["password"]
同样的，这里的username和password也是可选参数

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/metadata/utils/es_tools.py
> +    # TODO 要确认下这个超时是请求整体超时，还是连接超时
这里的TODO是不是还没完成，`METADATA_REQUEST_ES_TIMEOUT`这个我理解是请求超时，如果有数据返回，是不受这个的影响

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/metadata/models/storage.py
> +    def _get_index_infos(self, namespaced: str) -> Tuple[Dict[str, Dict[str, Any]], str]:
函数中出现了太多的"cat"和"indices"，而且又要求外面也需要传入这个，那建议写成枚举值。 这样调用者一眼就可以知道这个函数到底支持多少种类型

2024-08-31 03:01 UTC, liuwenping commented on bkmonitor/metadata/utils/es_tools.py
> +    if not isinstance(cluster, ClusterInfo):
这里建议用肯定的if语句，改为如果是 数字，则进入这个if

2024-08-31 04:42 UTC, liuwenping requested changes

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/apm/core/handlers/query/base.py
> +            pass
没看懂为啥这里忽略 KeyError，日志也不打印

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/apm/core/handlers/query/ebpf_query.py
> +class EbpfQuery(BaseQuery):
`EbpfQuery` 这个已经没有再使用了。可以删除掉

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +                )
疑问：为什么`return_fields`只需要不带括号的。进到这个带括号的逻辑时，并没有把metric_field加入到return_fields里

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +            return (self.query.high_mark or 0 - self.query.low_mark, 0)[self.query.high_mark is None]
首先这个写法并不推荐，一点也不pythnic，另外这里也有个BUG
BUG：当high_mark为None时，默认值变为了0，与原有的逻辑不符合（原有的逻辑默认值为1）

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +        interval = 0
BUG：这个默认值为0，估计是个BUG，聚合的场景下，建议默认按分钟聚合

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +                interval = time_agg_field.groupdict().get("second") or 0
同理，这里的默认值为0也不合理

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +        if self.query.group_hits_size:
建议：感觉原来>0的逻辑更明确直观

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +    def fill_values_to_record(cls, aggs: Dict[str, Any], record: Dict[str, Any], select_fields: List[Dict[str, Any]]):
建议：如何函数本身不需要给外面调用，建议统一都改为私有方法

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +    def extract_dimension_buckets(cls, dimension: str, aggs: Dict[str, Any]) -> List[Dict[str, Any]]:
重复：这个函数被重复写了多次
另外这个逻辑感觉也没有必要抽出来，如果是想忽略异常，那么使用get获取值即可

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/connection.py
> +            extra["use_full_index_names"] = True
建议：这三行是不是可以合并为一行,  都传递这个参数`use_full_index_names`

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/models/query.py
>  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
建议：如果这个文件没有扩展，建议把这个文件回滚，改动动作不要太大

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/models/sql/query.py
> +            "query": api.metadata.get_es_data,
BUG：这里需要回滚，在SAAS的场景下，是没有办法使用后台的代码

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/models/sql/query.py
> +            "query": api.metadata.get_es_data,
BUG：同理这里也需要回滚

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/models/sql/query.py
> +    def get_limit_range(cls, low=None, high=None, low_mark=None, high_mark=None):
建议：这里不建议直接从类身上把函数暴露出去，如果需要，建议把这个方法写到类的外面去

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +        self.add_system_filter_to_data_sources(self.data_sources)
建议：这个函数名建议使用更为底层的名称，而不是指名为system等名称。比如`预处理逻辑`, `特殊逻辑`等等

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> -        for data_source in self.data_sources:
建议：把这个for拆分为两个逻辑，并没有觉得代码更直观

另外也未看到功能的扩展，建议将代码回滚，以减少影响面

2024-08-31 04:42 UTC, liuwenping commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +                    # TODO 预留 total，后续看怎么处理
建议：这里写个TODO，预留这个total，感觉没有啥意义。 
这里把逻辑直接返回感觉更好，后面也没有进一步处理逻辑了

2024-08-31 06:35 UTC, ZhuoZhuoCrayon commented on bkmonitor/metadata/models/result_table.py
> +            table_id = query_table_id.replace("apm_global_", "apm_global.", 1)
@liuwenping 已确认并优化
之前 apm 后台对结果表做 `.` -> `_` 转换得到 ES 索引，走 datasource 后直接走结果表查询，所以这里的 `_` -> `.` 是多余的，已去除

2024-08-31 06:49 UTC, ZhuoZhuoCrayon commented on bkmonitor/query_api/resources.py
> +            required=False, label="索引全名列表（不为空优先使用", child=serializers.CharField(required=True, label="索引名")
@liuwenping 要精确到具体的物理索引；本意是想指定「具体的物理索引」，确实 `index_names` 更好，而且定义可以更泛，不一定非得是不包含通配符的索引，es client 也是如此 👇 

```
        :arg index: A comma-separated list of index names to search; use `_all`
            or empty string to perform the operation on all indices
```

2024-08-31 07:32 UTC, ZhuoZhuoCrayon commented on bkmonitor/metadata/utils/es_tools.py
> +    # TODO 要确认下这个超时是请求整体超时，还是连接超时
@liuwenping 是全局的请求超时配置

```
Global timeout can be set when constructing the client (see Connection’s timeout parameter) or on a per-request basis using request_timeout (float value in seconds) as part of any API call, this value will get passed to the perform_request method of the connection class:
```
* Refer：https://elasticsearch-py.readthedocs.io/en/v7.12.0/api.html?highlight=timeout#timeout

2024-08-31 07:49 UTC, ZhuoZhuoCrayon commented on bkmonitor/metadata/models/storage.py
> +    def _get_index_infos(self, namespaced: str) -> Tuple[Dict[str, Dict[str, Any]], str]:
已提取枚举类：`ESNamespacedClientType`

2024-08-31 08:01 UTC, ZhuoZhuoCrayon commented on bkmonitor/apm/core/handlers/query/base.py
> +            pass
已移除，会和其他异常一起捕获记录日志

2024-08-31 08:24 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +                )
这里是在 ES 场景下区分「聚合字段」和「返回字段」，例如 `select count(a), b from xxx`：
* `select_fields `: `["a"]`，用于构造 dsl 的 `aggs`
* `return_fields`: `["b"]`，用于构造 dsl 的 `_source`

因为 `select_fields` 以 `buckets` 返回，所以不需要出现在 `return_fields` 里

2024-08-31 09:15 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +            return (self.query.high_mark or 0 - self.query.low_mark, 0)[self.query.high_mark is None]
确实，之前的逻辑可以沿用，已回退

2024-08-31 09:55 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +    def extract_dimension_buckets(cls, dimension: str, aggs: Dict[str, Any]) -> List[Dict[str, Any]]:
1. 之前的逻辑是两个 get（还有 bug） -> `aggs.get(dimensions[i]).get("buckets")`，此处用异常代替边界处理似乎更好些，参考：[Python 工匠：在边界处思考](https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/15-thinking-in-edge-cases.md#%E8%8E%B7%E5%8F%96%E5%8E%9F%E8%B0%85%E6%AF%94%E8%AE%B8%E5%8F%AF%E7%AE%80%E5%8D%95eafp)


3. 重复部分：FtaEvent SQLCompiler（bkmonitor/data_source/backends/fta_event/compiler.py）的处理和父类不一样，已补充

```python
    @classmethod
    def _extract_dimension_buckets(cls, dimension: str, aggs: Dict[str, Any]) -> List[Dict[str, Any]]:
        if dimension.startswith(cls.TAGS_FIELD_PREFIX):
            return aggs[dimension]["key"]["value"]["buckets"]
        return aggs[dimension]["buckets"]
```

2024-08-31 09:58 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/connection.py
> +            extra["use_full_index_names"] = True
是的，一行就可以：`extra: Dict[str, Any] = {"use_full_index_names": params.pop("use_full_index_names", False)}`

2024-08-31 10:01 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/models/query.py
>  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
在 [bkmonitor/apm/core/handlers/query/builder.py](https://github.com/TencentBlueKing/bk-monitor/pull/2583/files#diff-f2b08cba301459c200ade24306747edcea9711b2b9034c5eb4fe67235d52401b) 复用了这里的逻辑，节省 200 行重复代码量，拆分的原因是上层分别复用这个类不同职责的接口

2024-08-31 10:11 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/models/sql/query.py
> +            "query": api.metadata.get_es_data,
1. 这里是 **API 调用**，和 `api.apm_api.query_es` 是一样的调用链路
![企业微信截图_1f990bc5-f4cb-4155-a714-fa07e8304e3f](https://github.com/user-attachments/assets/0fca9782-50c3-4ef7-af39-34efe2951f02)

2. 为什么不使用 `api.apm_api.query_es`？功能和 metadata 重合，是重复的代码逻辑，基于查询统一走 datasource + unifyquery 的原则，先收归，后面确认没有调用时把接口下掉

2024-08-31 10:29 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> -        for data_source in self.data_sources:
这里主要是考虑代码复用，`query_data` / `query_log` 会复用这段逻辑，所以做了下抽象

2024-08-31 10:32 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +        self.add_system_filter_to_data_sources(self.data_sources)
参照这个模块的命名风格，改为 `process_data_sources`

2024-08-31 10:36 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +                    # TODO 预留 total，后续看怎么处理
考量点在于，unifyquery（return `data`） 和 datasource 返回结构不一致（ `data, total`），需要屏蔽差异再返回；此处暂不修改，对接 unifyquery 的 PR 已经做了逻辑优化

2024-08-31 12:35 UTC, ZhuoZhuoCrayon commented on bkmonitor/bkmonitor/data_source/backends/elastic_search/compiler.py
> +        interval = 0
1. 看起来原先的逻辑是只要传了 `time_field`，就会默认补一个时间聚合：）
2. 时间聚合在原始日志、指标计算里是非必须的，这里的逻辑还原，加个开关，APM 场景才特殊处理

2024-09-02 14:14 UTC, unique0lai approved these changes

2024-09-11 03:53 UTC, liuwenping approved these changes

2024-09-11 03:53 UTC, merged