feat: 【产品优化】告警策略-批量操作-修改告警组 添加提示防止用户误操作 --story=118621315
TencentBlueKing/bk-monitor pull request #2696
Opened 2024-08-29 07:00 UTC by SevenBee

2024-08-29 07:00 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-monitor?pullRequest=2696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-monitor?pullRequest=2696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-monitor?pullRequest=2696) it.</sub>

2024-08-29 07:18 UTC, SevenBee commented
自测：
![image](https://github.com/user-attachments/assets/fda47feb-3f84-43e7-8cf8-8561b2c6e8f1)

- 覆盖替换操作
user_group: [2,3,4,5] -> [2]
![image](https://github.com/user-attachments/assets/5b6f084f-0168-4784-ad69-c69ba759084b)
![image](https://github.com/user-attachments/assets/9cf182e2-b9c6-464a-bc01-3e07a7400c29)

- 添加可选参数 append_keys 进行覆盖替换操作
user_group: [2] -> [3]
![image](https://github.com/user-attachments/assets/9cf182e2-b9c6-464a-bc01-3e07a7400c29)
![image](https://github.com/user-attachments/assets/7c52bc66-b042-4b23-a60b-57b70924671c)
![image](https://github.com/user-attachments/assets/4cba40d4-0d4d-428a-9399-80cc8eeeba82)

- 执行追加操作
在 append_keys 中添加 "user_groups"
user_group: [3] + [2,3,4] -> [2,3,4]

![image](https://github.com/user-attachments/assets/4cba40d4-0d4d-428a-9399-80cc8eeeba82)
![image](https://github.com/user-attachments/assets/95890868-d015-43fb-ad3e-6cc86fcbd493)
![image](https://github.com/user-attachments/assets/972bbb1d-bdf5-45e2-90e0-720585767b89)

2024-09-02 09:55 UTC, chenguo367 requested changes

2024-09-02 09:55 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +        if notice.get("append_keys"):
补充注释，这里追加的特殊逻辑。 引入了一个append_keys的 字段。

2024-09-03 01:35 UTC, SevenBee commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +        if notice.get("append_keys"):
Added comment

2024-09-03 01:40 UTC, SevenBee reviewed
添加更新告警通知的注释

2024-09-07 09:49 UTC, chenguo367 approved these changes

2024-09-07 09:49 UTC, merged