feat: APM 编辑触发通知 --story=119429883
TencentBlueKing/bk-monitor pull request #2717
Opened 2024-08-29 15:14 UTC by pegasusljn

2024-08-29 15:14 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-monitor?pullRequest=2717) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-monitor?pullRequest=2717) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-monitor?pullRequest=2717) it.</sub>

2024-08-30 13:21 UTC, liuwenping requested changes

2024-08-30 13:21 UTC, liuwenping commented on bkmonitor/packages/apm_web/tasks.py
> +                "业务ID：{bk_biz_id}, 业务名称：{bk_biz_name}, 更新者：{operator}，更新时间：{operate_time}"
这个内容需要修改一下，明确一下，是修改了什么

2024-08-30 13:21 UTC, liuwenping commented on bkmonitor/packages/apm_web/tasks.py
> +                "业务ID：{bk_biz_id}, 业务名称：{bk_biz_name}, 创建者：{operator}，创建时间：{operate_time}"
这里的内容也需要修改一下，创建应用后，并开启了哪些数据源能力

2024-08-30 13:21 UTC, liuwenping commented on bkmonitor/packages/apm_web/tasks.py
> +def report_apm_application_event(bk_biz_id, application_id, apm_event=APMEvent.APP_CREATE):
这里不用默认值，需要明确给出要传过来的内容是哪些

2024-09-02 11:43 UTC, pegasusljn commented on bkmonitor/packages/apm_web/tasks.py
> +                "业务ID：{bk_biz_id}, 业务名称：{bk_biz_name}, 创建者：{operator}，创建时间：{operate_time}"
已调整，新增开启数据源信息内容

2024-09-02 11:43 UTC, pegasusljn commented on bkmonitor/packages/apm_web/meta/resources.py
> +        )
新增应用，tips中设置data_soruce打开情况

2024-09-02 11:43 UTC, pegasusljn commented on bkmonitor/packages/apm_web/meta/resources.py
> +
更新app根据实际情况添加data_source开启提示

2024-09-02 11:43 UTC, pegasusljn commented on bkmonitor/packages/apm_web/tasks.py
> +                "业务ID：{bk_biz_id}, 业务名称：{bk_biz_name}, 更新者：{operator}，更新时间：{operate_time}"
同上, 新增开启数据源信息内容

2024-09-02 11:53 UTC, liuwenping approved these changes

2024-09-02 11:54 UTC, merged