feat: KafkaTailResource-支持SCRAM-SHA-512鉴权，使用confluent_kafka --story=119826512
TencentBlueKing/bk-monitor pull request #3102
Opened 2024-09-23 12:18 UTC by EASYGOING45

2024-09-23 12:26 UTC, liuwenping requested changes

2024-09-23 12:26 UTC, liuwenping commented on bkmonitor/metadata/resources/resources.py
> +            msg = consumer.poll(timeout=1.0)
这里是拉取最后的10条，不是卡在这里轮询

2024-09-23 12:26 UTC, liuwenping commented on bkmonitor/metadata/resources/resources.py
> +            'auto.offset.reset': 'earliest',
这里不对，从尾端拉取

2024-09-23 12:30 UTC, jacky15 commented on bkmonitor/metadata/resources/resources.py
> +            'sasl.mechanisms': 'SCRAM-SHA-512',
为什么要写死验证模式？复用is_ssl_verify、ssl_verification_mode等字段是否可以？

2024-09-23 12:30 UTC, jacky15 commented on bkmonitor/config/default.py
> +BKBASE_KAFKA_CLUSTER_ID_LIST = []
是否可以考虑在ClusterInfo记录中增加标记位，而非真的如此“临时”处理？

2024-09-24 01:25 UTC, EASYGOING45 commented on bkmonitor/metadata/resources/resources.py
> +            'auto.offset.reset': 'earliest',
已改为latest～

2024-09-24 01:25 UTC, EASYGOING45 commented on bkmonitor/config/default.py
> +BKBASE_KAFKA_CLUSTER_ID_LIST = []
已改为根据registered_system进行判断～

2024-09-24 03:26 UTC, shamcleren submitted a review, later dismissed
lgtm

2024-09-24 03:44 UTC, liuwenping requested changes

2024-09-24 03:44 UTC, liuwenping commented on bkmonitor/config/default.py
> +
减少改动，不要动这个文件

2024-09-24 03:44 UTC, liuwenping commented on bkmonitor/metadata/models/storage.py
> +    Note： 若涉及Kafka协议问题，需在SCRAM_SHA_512_KAFKA_CLUSTER_ID_LIST中添加对应的集群ID
这个注释不应该写到这里，看下是否还需要

2024-09-24 03:44 UTC, liuwenping commented on bkmonitor/metadata/resources/resources.py
> +                            raise KafkaException(msg.error())
这里不能直接抛异常，可以选择记录下来，
到最后的时候判断下，是否已经读取到数据，
如果读取到，则不需要把异常丢出去

2024-09-24 04:00 UTC, liuwenping requested changes

2024-09-24 04:00 UTC, liuwenping commented on bkmonitor/metadata/resources/resources.py
> +                                return result
这三行可以考虑去掉了

2024-09-24 04:05 UTC, liuwenping approved these changes

2024-09-24 04:05 UTC, merged