feat: monitor_web.strategies.resources.v2.GetTargetDetail接口优化 --story=119853107
TencentBlueKing/bk-monitor pull request #3187
Opened 2024-09-29 10:14 UTC by HACK-WU

2024-09-29 11:39 UTC, HACK-WU commented
自测截图：
* 第一次请求监控目标详细信息，请求成功
![image](https://github.com/user-attachments/assets/0bd6e9aa-4035-43e3-a8de-b5390ff641c5)
* 清空数据库中target的信息，依然能正常获取，证明缓存生效
![企业微信截图_17276091211177](https://github.com/user-attachments/assets/849d6ea4-4bd0-4e0a-b95b-be21869fb269)
*  之后清空缓存中的信息，此时数据库中也不存在target 的信息，再次获取target的详细信息，如下图可以看到并没有获取到监控目标详细信息了，符合预期
![企业微信截图_17276096009116](https://github.com/user-attachments/assets/d2cd7a14-3401-4e8f-af67-31a43982e189)

2024-09-30 03:36 UTC, chenguo367 requested changes

2024-09-30 03:36 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/tasks.py
> +        items = ItemModel.objects.filter(strategy_id__in=strategy_ids)
item只需要查询 strategy_id和target字段。

2024-09-30 03:36 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +    backend_cache_type = CacheType.CC_CACHE_ALWAYS
cache_user_related = Fasle
backend_cache_type

2024-09-30 03:36 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +            info = get_target_detail_with_cache.request({"strategy_id": item.strategy_id})
drf_resource提供更简洁的写法：
resource.strategies.get_target_detail_with_cache(strategy_id=item.strategy_id)
如果不能这么写，可以给下具体原因

2024-09-30 03:36 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +        bk_biz_id = self.strategy_target_mapping[strategy_id][0]
判定对象strategy_target_mapping是否存在

2024-10-14 09:26 UTC, tang202388 commented on bkmonitor/packages/monitor_web/tasks.py
> +                resource.strategies.get_target_detail_with_cache.request.refresh({"strategy_id": item.strategy_id})
设置strategy_id与(bk_biz_id, item.target)的映射关系是不是可以放在下面刷新缓存的for循环内，这样可以少一个循环

2024-10-14 09:37 UTC, tang202388 commented on bkmonitor/config/default.py
> +ENABLED_TARGET_CACHE_BK_BIZ_IDS = []
这个变量是不是可以再在bkmonitor/bkmonitor/define/global_config.py里面定义一下，方便配置需要缓存监控目标的业务ID列表

2024-10-16 13:28 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/tasks.py
> +                resource.strategies.get_target_detail_with_cache.request.refresh({"strategy_id": item.strategy_id})
问题不大

2024-10-18 06:16 UTC, HACK-WU commented on bkmonitor/config/default.py
> +ENABLED_TARGET_CACHE_BK_BIZ_IDS = []
已优化

2024-10-18 07:44 UTC, chenguo367 approved these changes

2024-10-18 07:44 UTC, merged