fix: metric V4数据状态兼容 --story=119969222
TencentBlueKing/bk-monitor pull request #3268
Opened 2024-10-11 11:11 UTC by pegasusljn

2024-10-11 12:41 UTC, liuwenping requested changes

2024-10-11 12:41 UTC, liuwenping commented on bkmonitor/packages/apm_web/handlers/backend_data_handler.py
> +        # Todo: v4链路暂未支持，暂时写死使用默认值返回
这里需要更新一下，除了状态字段无法获取，其他信息还是需要保持正确性

2024-10-12 03:22 UTC, pegasusljn commented on bkmonitor/packages/apm_web/handlers/backend_data_handler.py
> +        # Todo: v4链路暂未支持，暂时写死使用默认值返回
已经更新

2024-10-12 03:57 UTC, liuwenping approved these changes

2024-10-12 03:57 UTC, merged