feat: fta_web.alert.resources.MetricRecommendationResource接口优化 --story=119985548
TencentBlueKing/bk-monitor pull request #3320
Opened 2024-10-15 03:33 UTC by HACK-WU

2024-10-15 03:37 UTC, HACK-WU commented
新增了两个python依赖，需要额外下载安装
python-box==7.2.0
pandas== 2.0.3

2024-10-15 07:25 UTC, HACK-WU commented
自测截图：
# perform_request 方法测试
![image](https://github.com/user-attachments/assets/f0a7a557-41ce-457e-a392-b250f09d44bc)

2024-10-16 06:20 UTC, chenguo367 requested changes

2024-10-16 06:20 UTC, chenguo367 commented on bkmonitor/requirements.txt
> +pandas== 2.0.3
辛苦确认下引入新依赖的必要性，非必须功能尽量避免引入新的依赖。

2024-10-16 08:33 UTC, HACK-WU commented on bkmonitor/requirements.txt
> +pandas== 2.0.3
已提交了新代码，取消了上面两个新增的依赖

2024-10-17 03:16 UTC, chenguo367 requested changes

2024-10-17 03:16 UTC, chenguo367 commented on bkmonitor/packages/fta_web/alert/resources.py
> +            recommend_panel["feedback"] = feedback_results[
需要考虑key不存在的情况，这里可能会出现keyerror

2024-10-17 06:49 UTC, HACK-WU commented on bkmonitor/packages/fta_web/alert/resources.py
> +            recommend_panel["feedback"] = feedback_results[
已优化

2024-10-17 07:23 UTC, chenguo367 approved these changes

2024-10-17 07:23 UTC, merged