feat: profiling检索增加时间对比功能-后端代码 --story=119073372
TencentBlueKing/bk-monitor pull request #3349
Opened 2024-10-16 03:41 UTC by WuFantaotao

2024-10-24 13:24 UTC, liuwenping requested changes

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +            # print("diagram_dict: ",diagram_dict)
这类print代码不要提交上来

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +                # print(key, value)
同理

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +        # data = {k: v for diagram_dict in diagram_dicts for k, v in diagram_dict.items()}
临时调试的代码都不要提交上来

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +        print("options: ", options)
print代码需要去掉

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +                print(start, end)
print代码需要去掉

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +            start, end = self._enlarge_duration(start_time, end_time, offset=offset)
临时变量，不要覆盖掉参数start、end

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +                start, end = self._enlarge_duration(start_time, end_time, offset=offset)
同理，不要覆盖全局的start、end

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +        for diagram_dict in diagram_dicts:
这个for循环，没看懂

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +                offset=data["offset"],
data中一定会有offset吗，如果没有的话，建议使用get取值，同时提供默认值

2024-10-24 13:24 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/views.py
> +            start, end = self._enlarge_duration(start_time, end_time, offset=data["offset"])
建议不要覆盖全局里的start、end两个变量

2024-10-25 01:31 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +            # print("diagram_dict: ",diagram_dict)
已解決

2024-10-25 01:31 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +                # print(key, value)
已解決

2024-10-25 01:31 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +        print("options: ", options)
已解決

2024-10-25 01:37 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +            start, end = self._enlarge_duration(start_time, end_time, offset=offset)
diff_start_time, diff_end_time = self._enlarge_duration(data["diff_filter_labels"].pop("start", ""), data["diff_filter_labels"].pop("end", ""), offset=data.get("offset",0))

2024-10-25 01:37 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +        for diagram_dict in diagram_dicts:
調試用的

2024-10-25 01:38 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +            start, end = self._enlarge_duration(start_time, end_time, offset=data["offset"])
diff_start_time, diff_end_time = self._enlarge_duration(data["diff_filter_labels"].pop("start", ""), data["diff_filter_labels"].pop("end", ""), offset=data.get("offset",0))

2024-10-25 01:44 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +                offset=data["offset"],
offset是有默認值的：offset = serializers.IntegerField(label="偏移量(秒)", required=False, default=0)

2024-10-25 01:45 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +            start, end = self._enlarge_duration(start_time, end_time, offset=offset)
已更改變量名：       
 if query_start_time and query_end_time:
            query_start_time, query_end_time = self._enlarge_duration(query_start_time, query_end_time, offset=data.get("offset",0))

2024-10-25 01:46 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +                start, end = self._enlarge_duration(start_time, end_time, offset=offset)
已更改變量名：       
 if query_start_time and query_end_time:
            query_start_time, query_end_time = self._enlarge_duration(query_start_time, query_end_time, offset=data.get("offset",0))

2024-10-25 01:46 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +                print(start, end)
已去除：

2024-10-25 01:47 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/views.py
> +        # data = {k: v for diagram_dict in diagram_dicts for k, v in diagram_dict.items()}
已刪除

2024-10-25 02:46 UTC, liuwenping approved these changes

2024-10-25 02:46 UTC, merged