fix: 预计算队列分配问题修复 --bug=132572661
TencentBlueKing/bk-monitor pull request #3471
Opened 2024-10-22 11:24 UTC by rxwycdh

2024-10-22 13:19 UTC, liuwenping requested changes

2024-10-22 13:19 UTC, liuwenping commented on bkmonitor/apm/core/discover/precalculation/check.py
> +            if not data_id or data_id == "None":
这里建议增加一个类型判断，判断 `APM_TASK_KIND`

2024-10-22 13:19 UTC, liuwenping commented on bkmonitor/apm/core/discover/precalculation/check.py
> +        for i in ApmApplication.objects.all():
这里是不是要增加一个is_enabled的判断，或者从外层直接传递进来，看外层已经查询过一次应用列表

2024-10-22 13:19 UTC, liuwenping commented on bkmonitor/apm/task/tasks.py
> +    PreCalculateCheck.batch_remove(removed_tasks)
这里最好增加一个判断，超过5个以上的删除，则不进行，而是发告警出来

2024-10-23 03:24 UTC, rxwycdh commented on bkmonitor/apm/core/discover/precalculation/check.py
> +        for i in ApmApplication.objects.all():
这里不用增加 enabled 的判断，因为如果 enabled 为 false，不需要删除，bmw 那边获取不到数据

2024-10-23 03:24 UTC, rxwycdh commented on bkmonitor/apm/core/discover/precalculation/check.py
> +        for i in ApmApplication.objects.all():
已调整 application 获取方式

2024-10-23 03:24 UTC, rxwycdh commented on bkmonitor/apm/core/discover/precalculation/check.py
> +            if not data_id or data_id == "None":
上层已经进行过 kind 判断了，这里传进来的一定是 apm 的任务

2024-10-23 03:24 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    PreCalculateCheck.batch_remove(removed_tasks)
已加告警

2024-10-23 03:32 UTC, liuwenping approved these changes

2024-10-23 03:32 UTC, merged