feat: 事件中心查询语句报错： 处理阶段 : 已通知 AND 状态 : 未恢复  --story=120115468
TencentBlueKing/bk-monitor pull request #3621
Opened 2024-10-29 09:28 UTC by HACK-WU

2024-10-29 09:32 UTC, HACK-WU commented
测试，第一行为原查询内容，第二行为处理后的内容：

处理阶段 : 已通知
(is_handled : true) AND is_shielded : false

处理阶段 : 已确认 AND 状态 : 未恢复
is_ack : true AND 状态 : 未恢复

处理阶段 : 已通知 OR 处理阶段 : 已屏蔽 
is_handled : true OR is_shielded : true

处理阶段 : 已确认 AND 状态 : 未恢复 OR 处理阶段 : 已屏蔽 
is_ack : true AND 状态 : 未恢复 OR is_shielded : true

处理阶段 : 已通知 OR -处理阶段 : 已屏蔽 
(is_handled : true OR is_shielded : false) AND is_shielded : false


((处理阶段 : 已通知) AND 状态 : 未恢复)
((( is_handled : true ) AND 状态 : 未恢复)) AND is_shielded : false

2024-10-29 10:03 UTC, chenguo367 requested changes

2024-10-29 10:03 UTC, chenguo367 commented on bkmonitor/packages/fta_web/alert/utils.py
> +    >> '(is_handled : true AND 告警名称 : "VMStorage内存使用率" OR 状态 : 未恢复) AND is_handled : false'
is_handled -> is_shielded

2024-10-29 10:03 UTC, chenguo367 commented on bkmonitor/packages/fta_web/alert/utils.py
> +    tag = False
变量命名

2024-10-29 10:03 UTC, chenguo367 commented on bkmonitor/packages/fta_web/alert/utils.py
> +    >> '(is_handled : true AND 告警名称 : "VMStorage内存使用率" OR 状态 : 未恢复) AND is_handled : false'
### 肯定
处理阶段: 已通知
(is_handled: true AND is_shielded: false) 
处理阶段: 已通知 OR 处理阶段: 已屏蔽
(is_handled: true AND is_shielded: false)  OR  is_shielded: true

### NOT
NOT 处理阶段: 已通知
NOT (is_handled: true AND is_shielded: false)

2024-10-29 11:31 UTC, HACK-WU commented
测试,第一行为原查询语句，第二行为处理过后的语句

处理阶段 : 已通知
(is_handled : true AND is_shielded : false)

处理阶段: 已通知 OR 处理阶段: 已屏蔽
(is_handled : true AND is_shielded : false) OR is_shielded : true

NOT 处理阶段: 已通知
NOT (is_handled : true AND is_shielded : false)

处理阶段 : 已确认 AND 状态 : 未恢复
is_ack : true AND 状态 : 未恢复

处理阶段 : 已通知 OR 处理阶段 : 已屏蔽 
(is_handled : true AND is_shielded : false) OR is_shielded : true

处理阶段 : 已确认 AND 状态 : 未恢复 OR 处理阶段 : 已屏蔽 
is_ack : true AND 状态 : 未恢复 OR is_shielded : true

NOT 处理阶段 : 已通知 OR -处理阶段 : 已屏蔽 
NOT (is_handled : true AND is_shielded : false) OR -is_shielded : true

处理阶段 : 已确认 AND 状态 : 未恢复 OR -处理阶段 : 已屏蔽 
is_ack : true AND 状态 : 未恢复 OR -is_shielded : true

((处理阶段 : 已通知) AND 状态 : 未恢复)
(((is_handled : true AND is_shielded : false) ) AND 状态 : 未恢复)

2024-11-07 12:39 UTC, chenguo367 approved these changes

2024-11-07 12:41 UTC, merged