fix: profiling数据查询三步简化成一步
TencentBlueKing/bk-monitor pull request #3709
Opened 2024-11-04 08:26 UTC by WuFantaotao

2024-11-05 13:33 UTC, rxwycdh approved these changes, later dismissed

2024-11-05 13:33 UTC, rxwycdh commented on bkmonitor/apm/core/discover/profile/service.py
> +                svr=result_dict.get("service_name","")
如果这三个值都没有，直接 continue，查出来的可能也是重复的数据

2024-11-08 01:50 UTC, WuFantaotao commented on bkmonitor/apm/core/discover/profile/service.py
> +                svr=result_dict.get("service_name","")
# 如果这三个值都没有，直接 continue，查出来的可能也是重复的数据
                if not col_type and not sample_type and not svr:
                    logger.info(
                        f"[ProfileServiceDiscover] " f"service_name: {svr}, type: {col_type}, sample_type: {sample_type} 无值时，查出来的可能也是重复的数据！！！"
                    )
                    continue

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/core/discover/profile/service.py
> +                        f"[ProfileServiceDiscover] " f"service_name: {svr}, type: {col_type}, sample_type: {sample_type} 无值时，查出来的可能也是重复的数据！！！"
和其他日志一样保持代码风格，使用英文日志

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +        app_name = serializers.CharField(label="应用名称", max_length=50)
这些参数，都可以是可选的，application_id 不一定需要传

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +            raise CustomException("bk_biz_id 和 space_uid 至少提供一个")
这里应该是三种情况，不需要固定用户一定要传 bk_biz_id 或者 space_uid。
1. 如果有 application_id 
2. 如果有 bk_biz_id + app_name
3. 如果有 space_uid + app_name

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +            raise CustomException("bk_biz_id 和 space_uid 至少提供一个")
另外，如果没有特殊说明，不需要使用 CustomException，按照平时的逻辑直接 raise 即可

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +            bk_biz_id=SpaceApi.get_space_detail(space_uid=space_uid).bk_biz_id
是否有可能获取不到的情况

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +        return ApmApplication.objects.get(id=application_id, app_name=app_name, bk_biz_id=bk_biz_id)
查询条件也需要对上面说的每种情况进行调整

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +class ApplicationInfoResource(ApiAuthResource):
继承这个 resource 的原因是什么

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +        bk_biz_id=validated_request_data.get("bk_biz_id","")
是不是没有执行 pre_commit?

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +        return Response({"message": f"删除应用 {app_name} 成功"})
有封装 response 返回的，你看其他 resource 也没有直接用 Response 返回，为什么这里会选择用 Response 返回？

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/apm/resources.py
> +        DeleteApplicationResource()(bk_biz_id=bk_biz_id, app_name=app_name)
检查一下应用是否存在再调用

2024-11-08 06:28 UTC, rxwycdh commented on bkmonitor/core/drf_resource/exceptions.py
> +    message_tpl = _lazy("{msg}")
不用再继承了，直接用原来的吧，因为这里是公共代码，写在这里不太好

2024-11-08 06:47 UTC, WuFantaotao commented on bkmonitor/apm/core/discover/profile/service.py
> +                        f"[ProfileServiceDiscover] " f"service_name: {svr}, type: {col_type}, sample_type: {sample_type} 无值时，查出来的可能也是重复的数据！！！"
f"[ProfileServiceDiscover] " f"when service_name: {svr}, type: {col_type}, sample_type: {sample_type} has no value, the data found may also be duplicate data! ! !！！！"

2024-11-08 06:50 UTC, WuFantaotao commented on bkmonitor/core/drf_resource/exceptions.py
> +    message_tpl = _lazy("{msg}")
已删除

2024-11-08 07:03 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +        app_name = serializers.CharField(label="应用名称", max_length=50)
application_id = serializers.IntegerField(label="应用id", required=False, default="")
        bk_biz_id = serializers.IntegerField(label="业务id", required=False, default="")
        app_name = serializers.CharField(label="应用名称", max_length=50,default="")
        space_uid = serializers.CharField(label="空间唯一标识", required=False, default="")

2024-11-08 07:18 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +            bk_biz_id=SpaceApi.get_space_detail(space_uid=space_uid).bk_biz_id
bk_biz_id = SpaceApi.get_space_detail(space_uid=space_uid).bk_biz_id
            if bk_biz_id:
                return ApmApplication.objects.get(bk_biz_id=bk_biz_id, app_name=app_name)
            else:
                raise ValueError("Missing required fields: application_id ,or bk_biz_id and app_name, or space_uid and app_name")

2024-11-08 07:19 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +class ApplicationInfoResource(ApiAuthResource):
ApiAuthResource有权限认证，现已改回

2024-11-08 07:21 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +        return Response({"message": f"删除应用 {app_name} 成功"})
已删除

2024-11-08 07:22 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +            raise CustomException("bk_biz_id 和 space_uid 至少提供一个")
if application_id:
            return ApmApplication.objects.get(id=application_id)
        elif bk_biz_id and app_name:
            return ApmApplication.objects.get(bk_biz_id=bk_biz_id, app_name=app_name)
        elif space_uid and app_name:
            bk_biz_id = SpaceApi.get_space_detail(space_uid=space_uid).bk_biz_id
            if bk_biz_id:
                return ApmApplication.objects.get(bk_biz_id=bk_biz_id, app_name=app_name)
            else:
                raise ValueError("Missing required fields: application_id ,or bk_biz_id and app_name, or space_uid and app_name")
        else:
            raise ValueError("Missing required fields: application_id ,or bk_biz_id and app_name, or space_uid and app_name")

2024-11-08 07:22 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +        return ApmApplication.objects.get(id=application_id, app_name=app_name, bk_biz_id=bk_biz_id)
if application_id:
            return ApmApplication.objects.get(id=application_id)
        elif bk_biz_id and app_name:
            return ApmApplication.objects.get(bk_biz_id=bk_biz_id, app_name=app_name)
        elif space_uid and app_name:
            bk_biz_id = SpaceApi.get_space_detail(space_uid=space_uid).bk_biz_id
            if bk_biz_id:
                return ApmApplication.objects.get(bk_biz_id=bk_biz_id, app_name=app_name)
            else:
                raise ValueError("Missing required fields: application_id ,or bk_biz_id and app_name, or space_uid and app_name")
        else:
            raise ValueError("Missing required fields: application_id ,or bk_biz_id and app_name, or space_uid and app_name")

2024-11-08 07:25 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +        DeleteApplicationResource()(bk_biz_id=bk_biz_id, app_name=app_name)
在删除函数里已经有检测了
class DeleteApplicationResource(Resource):
    class RequestSerializer(serializers.Serializer):
        bk_biz_id = serializers.IntegerField(label="业务id")
        app_name = serializers.CharField(label="应用名称")

    def perform_request(self, data):
        app = Application.objects.filter(bk_biz_id=data["bk_biz_id"], app_name=data["app_name"]).first()
        if not app:
            raise ValueError(_("应用{}不存在").format(data['app_name']))
        Application.delete_plugin_config(app.application_id)
        api.apm_api.delete_application(application_id=app.application_id)
        app.delete()
        return True

2024-11-11 04:14 UTC, liuwenping requested changes

2024-11-11 04:14 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +from apm_web.models import Application, LogServiceRelation
后端代码，尽量不要这样引入web的代码，如果非得引入，请放到函数里，不要放到文件头

2024-11-11 04:14 UTC, liuwenping commented on bkmonitor/apm/resources.py
> +            app = Application.objects.filter(application_id=application_id).first()
底下这几行删除应用的逻辑重复率太高了。需要抽取出来。  看上去就是根据bk_biz_id+app_name来删除应用

2024-11-11 07:12 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +from apm_web.models import Application, LogServiceRelation
已修改

2024-11-11 07:12 UTC, WuFantaotao commented on bkmonitor/apm/resources.py
> +            app = Application.objects.filter(application_id=application_id).first()
已抽取

2024-11-12 08:25 UTC, liuwenping approved these changes

2024-11-12 08:25 UTC, liuwenping commented
LGTM

2024-11-12 08:25 UTC, merged