fix: 修复 lucene 检索 TraceID 超时问题 --bug=133360193
TencentBlueKing/bk-monitor pull request #3722
Opened 2024-11-04 14:03 UTC by ZhuoZhuoCrayon

2024-11-04 14:15 UTC, ZhuoZhuoCrayon commented
判断是否为 Trace & SpanID，是的话转为精确查询

![image](https://github.com/user-attachments/assets/50eab5a2-c384-4463-9d1c-c9279c775798)

2024-11-20 04:02 UTC, liuwenping requested changes

2024-11-20 04:02 UTC, liuwenping commented on bkmonitor/packages/apm_web/handlers/trace_handler/query.py
> +        regx: Any = re.compile(r"^[0-9a-f]{32}$")
把这个整成为常量

2024-11-20 04:02 UTC, liuwenping commented on bkmonitor/packages/apm_web/handlers/trace_handler/query.py
> +        regx: Any = re.compile(r"^[0-9a-f]{16}$")
这个也设置为常量

2024-11-20 04:02 UTC, liuwenping commented on bkmonitor/packages/apm_web/handlers/trace_handler/query.py
>          _query_string: str
这里的regx也需要设置为常量

2024-11-21 01:48 UTC, liuwenping approved these changes

2024-11-21 01:48 UTC, merged