fix: 修改task.py中的topo_discover_cron函数，新增功能半小时内新创建的应用每 2 分钟执行一次拓扑发现
TencentBlueKing/bk-monitor pull request #3857
Opened 2024-11-12 11:57 UTC by WuFantaotao

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/packages/apm_web/constants.py
> +    APM_NEW_APPLICATION = "apm:new_application:"
仿照 APP_SERVICE_STATUS_KEY 的命名规范，保持风格统一。
APM_APPLICATION_QUICK_REFRESH = "apm:application:quick_refresh:{application_id}"

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/config/default.py
> +NEW_APPLICATION_REFRESH_RATE = 2 * 60
NEW_APPLICATION_REFRESH_RATE =》 APPLICATION_QUICK_REFRESH_INTERVAL = 120

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("NEW_APPLICATION_REFRESH_RATE", slz.BooleanField(label=_("新建应用的刷新频率，每 2 分钟执行一次拓扑发现"), default=2 * 60)),
不需要后面的：“每 2 分钟执行一次拓扑发现”，因为 2 分钟是值，而不是对这个变量的解释

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    from apm_web.constants import ApmCacheKey
这里不要引 apm_web，在 api 侧再写一个类，不然引入的地方越来越多了

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    cache = Cache("cache")
这个可以放在方法外层，不需要每次新建连接

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    half_hour_ago = now - datetime.timedelta(minutes=30)
这个 30，也做成可配置的

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    amp_app_queryset = ApmApplication.objects.filter(create_time__gt=half_hour_ago)
amp 写错了，注意命名

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +    amp_app_queryset = ApmApplication.objects.filter(create_time__gt=half_hour_ago)
amp_app_queryset -> newly_created_applications

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +        if cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{amp_app.id}"):
用 format，不要用这个，避免替换的位置不对

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +            )  # 60*2
这个注释不需要

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +        bk_biz_id, app_name, app_id, create_time = application
create_time 哪里有用到？

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +        if not cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{app_id}"):
是否能用 exist 代替 get

2024-11-12 14:03 UTC, rxwycdh commented on bkmonitor/apm/task/tasks.py
> +        if cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{amp_app.id}"):
是否能够 exist 代替 get

2024-11-13 04:13 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +        if cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{amp_app.id}"):
if not cache.exists(ApmCacheKey.APM_APPLICATION_QUICK_REFRESH.format(application_id=app_id)):

2024-11-13 04:13 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +        if not cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{app_id}"):
if not cache.exists(ApmCacheKey.APM_APPLICATION_QUICK_REFRESH.format(application_id=app_id)):

2024-11-13 04:14 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/constants.py
> +    APM_NEW_APPLICATION = "apm:new_application:"
APM_APPLICATION_QUICK_REFRESH = "apm:application:quick_refresh:{application_id}"

2024-11-13 04:16 UTC, WuFantaotao commented on bkmonitor/config/default.py
> +NEW_APPLICATION_REFRESH_RATE = 2 * 60
("APPLICATION_QUICK_REFRESH_INTERVAL", slz.BooleanField(label=_("新建应用的刷新频率"), default=120)),

2024-11-13 04:16 UTC, WuFantaotao commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("NEW_APPLICATION_REFRESH_RATE", slz.BooleanField(label=_("新建应用的刷新频率，每 2 分钟执行一次拓扑发现"), default=2 * 60)),
("APPLICATION_QUICK_REFRESH_INTERVAL", slz.BooleanField(label=_("新建应用的刷新频率"), default=120)),

2024-11-13 04:16 UTC, WuFantaotao commented on bkmonitor/config/default.py
> +NEW_APPLICATION_REFRESH_RATE = 2 * 60
APPLICATION_QUICK_REFRESH_INTERVAL = 120

2024-11-13 04:17 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +    from apm_web.constants import ApmCacheKey
class ApmCacheKey:
    """一些 APM 的缓存 Key"""

    # 30钟内新建应用的id在缓存中的key
    APM_APPLICATION_QUICK_REFRESH = "apm:application:quick_refresh:{application_id}"

2024-11-13 04:18 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +        if cache.get(f"{ApmCacheKey.APM_NEW_APPLICATION}{amp_app.id}"):
for apm_app in newly_created_applications:
        if cache.exists(ApmCacheKey.APM_APPLICATION_QUICK_REFRESH.format(application_id=apm_app.id)):
            continue

2024-11-13 04:18 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +            )  # 60*2
已删除

2024-11-13 04:19 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +    amp_app_queryset = ApmApplication.objects.filter(create_time__gt=half_hour_ago)
newly_created_applications = ApmApplication.objects.filter(create_time__gt=half_hour_ago)

2024-11-13 06:40 UTC, rxwycdh commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("APPLICATION_QUICK_REFRESH_DELTA", slz.BooleanField(label=_("新建应用的创建时间到当前时间的时长范围"), default=30)),
为什么这个是 bool？

2024-11-13 06:44 UTC, WuFantaotao commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("APPLICATION_QUICK_REFRESH_DELTA", slz.BooleanField(label=_("新建应用的创建时间到当前时间的时长范围"), default=30)),
("APPLICATION_QUICK_REFRESH_INTERVAL", slz.IntegerField(label=_("新建应用的刷新频率"), default=120)),
        ("APPLICATION_QUICK_REFRESH_DELTA", slz.IntegerField(label=_("新建应用的创建时间到当前时间的时长范围"), default=30)),

2024-11-13 09:20 UTC, liuwenping requested changes

2024-11-13 09:20 UTC, liuwenping commented on bkmonitor/apm/task/tasks.py
> +cache = Cache("cache")
这个cache可以去掉了

2024-11-13 09:20 UTC, liuwenping commented on bkmonitor/apm/task/tasks.py
> +from alarm_backends.core.storage.redis import Cache
这个也可以去掉了

2024-11-13 09:20 UTC, liuwenping commented on bkmonitor/apm/task/tasks.py
> +                    if index % interval_quick == slug_quick:
这里的取模，用 app_id 来取模，会不会好些
`app_id % interval_quick == slug_quick`

2024-11-13 09:20 UTC, liuwenping commented on bkmonitor/apm/task/tasks.py
> +                    if index % interval == slug:
同上，取模使用app_id

2024-11-13 09:20 UTC, liuwenping commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("APPLICATION_QUICK_REFRESH_DELTA", slz.IntegerField(label=_("新建应用的创建时间到当前时间的时长范围"), default=30)),
这里的两个常量，都补充上APM的前缀，然后位置放到APM的常量一起

2024-11-13 09:48 UTC, WuFantaotao commented on bkmonitor/apm/task/tasks.py
> +                    if index % interval == slug:
已修改

2024-11-13 09:48 UTC, WuFantaotao commented on bkmonitor/bkmonitor/define/global_config.py
> +        ("APPLICATION_QUICK_REFRESH_DELTA", slz.IntegerField(label=_("新建应用的创建时间到当前时间的时长范围"), default=30)),
已修改

2024-11-13 11:42 UTC, liuwenping approved these changes

2024-11-13 11:42 UTC, merged