feat: UpdatePartialStrategyV2Resource针对用户组批量更新优化 --story=120720224
TencentBlueKing/bk-monitor pull request #3907
Opened 2024-11-15 07:12 UTC by tang202388

2024-11-18 08:07 UTC, tang202388 commented
自测截图：
1、批量修改用户组前表strategy_action_relation和表action_config数据如下：
![image](https://github.com/user-attachments/assets/38c17649-550e-4f25-bce5-2caccc711ce7)
![image](https://github.com/user-attachments/assets/f4e9967e-8446-4c86-a920-36e5cd5e967e)
2、将策略id为1,2,3,4的策略批量替换用户组id为1和2，可以正常操作没有报错，修改用户组后表strategy_action_relation和表action_config的字段正常更新：
![image](https://github.com/user-attachments/assets/a4019641-9873-400f-8846-ba6430d6b6af)
![image](https://github.com/user-attachments/assets/d3c8388d-91f8-45c3-b09b-22e282e79c0f)

2024-11-26 12:05 UTC, chenguo367 requested changes

2024-11-26 12:05 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +                if update_method == getattr(self, "update_notice", None):
update_method: Callable[[Strategy, Any], None] = getattr(self, f"update_{key}", None)
                if update_method == getattr(self, "update_notice", None):

2024-11-26 12:05 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +                if update_method == getattr(self, "update_notice", None):
这里直接判断key == "notice"就可以了吧？

2024-11-26 12:05 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/strategies/resources/v2.py
> +                if update_method == getattr(self, "update_notice", None):
另外看起来这里是一个单独处理update_notice 的逻辑，所以当key 是 notice的时候， 直接调用self.update_notice就可以了

2024-11-27 02:26 UTC, chenguo367 approved these changes

2024-11-27 02:29 UTC, merged