feat: APM 服务发现增加识别框架、SDK、平台 --story=120997477
TencentBlueKing/bk-monitor pull request #4157
Opened 2024-12-02 12:12 UTC by rxwycdh

2024-12-03 11:57 UTC, ZhuoZhuoCrayon commented on bkmonitor/apm/migrations/0045_auto_20241203_1450.py
> +            field=models.JSONField(null=True, verbose_name="服务框架"),
系统类型

2024-12-03 11:57 UTC, ZhuoZhuoCrayon commented on bkmonitor/apm/models/topo.py
> +    system = models.JSONField("服务框架", null=True)
系统类型

2024-12-04 04:49 UTC, liuwenping requested changes

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/models/config.py
> +    APM_TOPO_PLATFORM_NODE = "node"
不同分类，建议这里用一个换行区分一下。 PLATFORM 和 framework 的挨到一起了

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/models/config.py
> +            "type": DiscoverRuleType.SYSTEM.value,
这里的`SYSTEM`取名为`FRAMEWORK`会不会更合适，且统一一点

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/models/config.py
> +            "type": DiscoverRuleType.SYSTEM.value,
同理，建议统一为`FRAMEWORK`

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/models/config.py
> +            update_instances, fields=["endpoint_key", "instance_key", "topo_kind", "predicate_key", "sort", "type"]
这里`init_builtin_config`大概率全新部署会报错，因为这里加了一个`type`字段

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/constants.py
> +    def list_discover_sorts(cls):
这个新增方法全局搜了下，没有地方使用

2024-12-04 04:49 UTC, liuwenping commented on bkmonitor/apm/core/discover/node.py
> +                        update_instances.update({k: v})
不同批次的数据，应该会存在同一个key的情况，这里的是直接update，那也就是说直接使用最后的结果。看上去有点不对，是不是应该合并起来

2024-12-04 08:19 UTC, liuwenping approved these changes

2024-12-04 08:20 UTC, merged