feat: 屏蔽新增标签字段，API支持基于标签的检索 --story=121036813
TencentBlueKing/bk-monitor pull request #4203
Opened 2024-12-04 03:55 UTC by HACK-WU

2024-12-04 04:04 UTC, HACK-WU commented
测试内容：
https://github.com/HACK-WU/bk_monitor_test/blob/master/shield/resources/fronted_resources/test_frontend_shield_list.ipynb

2024-12-04 07:05 UTC, chenguo367 requested changes

2024-12-04 07:05 UTC, chenguo367 commented on bkmonitor/bkmonitor/models/base.py
> +    label = models.CharField(verbose_name="标签", max_length=32, default="", blank=True, db_index=True)
max_length = 255

2024-12-09 12:41 UTC, chenguo367 approved these changes

2024-12-09 12:41 UTC, merged