feat: Grafana10 仪表盘旧 panel 迁移 --story=120814592
TencentBlueKing/bk-monitor pull request #4221
Opened 2024-12-04 08:08 UTC by tang202388

2024-12-04 08:13 UTC, tang202388 commented
graph -> timeseries自测截图：
![image](https://github.com/user-attachments/assets/cee94bb5-175b-401b-ab7d-8a1a6e466a1f)
1、需要迁移的dashboard的graph面板类型的测试数据：
```python
test_dashboard = {
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": True,
        "hide": True,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": False,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": True,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 8,
  "links": [],
  "liveNow": False,
  "panels": [
    {
        "aliasColors": {},
        "bars": False,
        "dashLength": 10,
        "dashes": False,
        "datasource": {
            "type": "bkmonitor-timeseries-datasource",
            "uid": "000000002"
        },
        "fieldConfig": {
            "defaults": {
                "links": []
            },
            "overrides": []
        },
        "fill": 1,
        "fillGradient": 0,
        "gridPos": {
            "h": 12,
            "w": 24,
            "x": 0,
            "y": 1
        },
        "hiddenSeries": False,
        "id": 10,
        "legend": {
            "alignAsTable": True,
            "avg": False,
            "current": True,
            "max": True,
            "min": True,
            "rightSide": True,
            "show": True,
            "total": False,
            "values": True
        },
        "lines": True,
        "linewidth": 1,
        "nullPointMode": "null",
        "options": {
            "alertThreshold": True
        },
        "percentage": False,
        "pluginVersion": "9.0.2",
        "pointradius": 2,
        "points": False,
        "renderer": "flot",
        "seriesOverrides": [],
        "spaceLength": 10,
        "stack": False,
        "steppedLine": False,
        "targets": [
            {
                "alias": "$tag_handler",
                "datasource": {
                    "type": "bkmonitor-timeseries-datasource",
                    "uid": "000000002"
                },
                "interval": "",
                "only_promql": True,
                "refId": "A",
                "source": "sum(bkbcs_k8swatch_queue_handler_total_num{bcs_cluster_id=~\"$cluster_id\", handler!~\"writer_normal_queue|writer_alarm_queue\"}) by(handler)"
            }
        ],
        "thresholds": [],
        "timeRegions": [],
        "title": "handler类型队列长度",
        "tooltip": {
            "shared": True,
            "sort": 0,
            "value_type": "individual"
        },
        "type": "graph",
        "xaxis": {
            "mode": "time",
            "show": True,
            "values": []
        },
        "yaxes": [
            {
                "$$hashKey": "object:2964",
                "format": "short",
                "logBase": 1,
                "show": True
            },
            {
                "$$hashKey": "object:2965",
                "format": "short",
                "logBase": 1,
                "show": True
            }
        ],
        "yaxis": {
            "align": False
        }
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "default",
  "title": "demo2",
  "uid": "YonyJQGHk",
  "version": 3,
  "weekStart": ""
}
```
2、迁移为timeseries面板的数据：
![image](https://github.com/user-attachments/assets/51a4b4fe-1e75-48a6-9c73-e9a8dcac1b2c)

2024-12-06 08:09 UTC, unique0lai requested changes

2024-12-06 08:09 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +        dashboard_info = api.grafana.get_dashboard_by_uid(org_id=org_id, uid=params["dashboard_uid"])
这里的查询和后面的保存，可以改成直接用 bk_dataview下的model 操作

2024-12-06 08:09 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +        for panel in dashboard.get("panels", []):
panel 存在 row 的情况，还需要再次遍历row 下的 panels

2024-12-06 08:09 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +        folder_id = serializers.IntegerField(label="目录ID", required=True)
folder_id 没必要传，dashboard_uid 查出来的信息里面已经有 folder_id 了。如果使用 model 操作也用不上 folder_id 了

2024-12-06 08:09 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +        draw_style = next((draw_style_map[key] for key in draw_style_map if old_panel.get(key, False)), "line")
这个写法太绕了，不太利于理解

2024-12-06 08:09 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +            threshold_steps.append({"color": f"{randint(0, 0xFFFFFF):06X}", "value": threshold.get("value")})
这样可能会随机出黑色这种奇怪的颜色，阈值一般不会配置太多，可以考虑枚举一些就行了
可以考虑直接用 grafana 10 自动生成的颜色
<img width="496" alt="image" src="https://github.com/user-attachments/assets/b88ee0f2-c5af-4569-bf54-5d17ca6576c4">

2024-12-09 08:30 UTC, tang202388 commented
自测截图：
老版table -> 新版table
![image](https://github.com/user-attachments/assets/e525116a-3acd-408a-b100-cbe6e75a9529)
1、需要迁移的dashboard的老版table面板类型的测试数据：
```python
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": True,
        "hide": True,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": False,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": True,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 8,
  "links": [],
  "liveNow": False,
  "panels": [
{
  "datasource": {
    "type": "bkmonitor-timeseries-datasource",
    "uid": "000000002"
  },
  "columns": [
    {
      "$$hashKey": "object:247",
      "text": "Current",
      "value": "current"
    }
  ],
  "fontSize": "100%",
  "gridPos": {
    "h": 8,
    "w": 5,
    "x": 0,
    "y": 214
  },
  "id": 45,
  "pluginVersion": "6.2.5",
  "scroll": True,
  "showHeader": True,
  "sort": {
    "col": 0,
    "desc": True
  },
  "styles": [
    {
      "alias": "Time",
      "align": "auto",
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "pattern": "Time",
      "type": "date",
      "$$hashKey": "object:291"
    },
    {
      "alias": "Time",
      "align": "auto",
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 1,
      "pattern": "Current",
      "thresholds": [],
      "type": "number",
      "unit": "s",
      "$$hashKey": "object:292"
    }
  ],
  "targets": [
    {
      "alias": "$tag_process_name",
      "cluster": [],
      "datasource": {
        "type": "bkmonitor-timeseries-datasource",
        "uid": "000000002"
      },
      "display": False,
      "expression": "",
      "host": [],
      "module": [],
      "only_promql": True,
      "query_configs": [],
      "refId": "A",
      "source": "avg((time()-process_start_time_seconds{bk_app_code=~\"$bk_app_code\", bk_domain=~\"$bk_domain\"})) by (process_name)"
    }
  ],
  "title": "系统运行时长",
  "transform": "timeseries_aggregations",
  "type": "table-old",
  "pageSize": None
}
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "default",
  "title": "demo2",
  "uid": "YonyJQGHk",
  "version": 3,
  "weekStart": ""
}
```
2、迁移为新版table面板的数据：
![image](https://github.com/user-attachments/assets/5edabb77-6ee0-4232-bca6-087eedf940b4)

2024-12-09 09:02 UTC, unique0lai requested changes

2024-12-09 09:02 UTC, unique0lai commented on bkmonitor/packages/monitor_web/grafana/resources/manage.py
> +            if panel.get("type") == "raw":
row写错了成 raw 了，记得测试一下这种情况

2024-12-10 03:05 UTC, tang202388 commented
自测截图：
row类型中：graph -> timeseries,  老版table -> 新版table
![image](https://github.com/user-attachments/assets/107b9918-99e8-42a6-b904-59dd87f4a464)
1、需要迁移的dashboard的row面板类型的测试数据：
```python
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": True,
        "hide": True,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": False,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "description": "",
  "editable": True,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 1,
  "id": 2650,
  "links": [],
  "liveNow": False,
  "panels": [
    {
      "collapsed": True,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 194,
      "panels": [
        {
          "columns": [],
          "datasource": {
            "type": "bkmonitor-timeseries-datasource",
            "uid": "000000002"
          },
          "fontSize": "100%",
          "gridPos": {
            "h": 8,
            "w": 13,
            "x": 0,
            "y": 1
          },
          "id": 47,
          "interval": "1m",
          "scroll": True,
          "showHeader": True,
          "sort": {
            "desc": False
          },
          "styles": [
            {
              "alias": "Num",
              "align": "auto",
              "dateFormat": "YYYY-MM-DD HH:mm:ss",
              "pattern": "Value",
              "type": "number",
              "unit": "short"
            },
            {
              "alias": "",
              "align": "auto",
              "colors": [
                "rgba(245, 54, 54, 0.9)",
                "rgba(237, 129, 40, 0.89)",
                "rgba(50, 172, 45, 0.97)"
              ],
              "pattern": "/.*/",
              "thresholds": [],
              "type": "number",
              "unit": "short"
            }
          ],
          "targets": [
            {
              "alias": "$tag_handler",
              "cluster": [],
              "datasource": {
                "type": "bkmonitor-timeseries-datasource",
                "uid": "000000002"
              },
              "display": False,
              "expression": "",
              "host": [],
              "module": [],
              "only_promql": True,
              "query_configs": [],
              "refId": "A",
              "source": "sum(cmdb_http_request_total{status_code=~\"4.*|5.*\",bk_app_code=~\"$bk_app_code\", bk_domain=~\"$bk_domain\"}) by (status_code, handler)"
            }
          ],
          "title": "Error Request Address",
          "transform": "timeseries_to_rows",
          "type": "table-old"
        },
        {
          "aliasColors": {},
          "bars": False,
          "dashLength": 10,
          "dashes": False,
          "datasource": {
            "type": "bkmonitor-timeseries-datasource",
            "uid": "000000002"
          },
          "fieldConfig": {
            "defaults": {
              "links": []
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 9
          },
          "hiddenSeries": False,
          "id": 179,
          "legend": {
            "avg": False,
            "current": False,
            "max": False,
            "min": False,
            "show": True,
            "total": False,
            "values": False
          },
          "lines": True,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": True
          },
          "percentage": False,
          "pluginVersion": "10.4.10",
          "pointradius": 2,
          "points": False,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": False,
          "steppedLine": False,
          "targets": [
            {
              "alias": "进程操作延迟",
              "cluster": [],
              "datasource": {
                "type": "bkmonitor-timeseries-datasource",
                "uid": "000000002"
              },
              "display": False,
              "expression": "",
              "hide": False,
              "host": [],
              "module": [],
              "only_promql": True,
              "query_configs": [],
              "refId": "D",
              "source": "sum(increase(cmdb_http_request_duration_millisecond_sum{process_name=\"proc\",bk_app_code=~\"$bk_app_code\", bk_domain=~\"$bk_domain\"}[30s])) / sum(increase(cmdb_http_request_duration_millisecond_count{process_name=\"proc\",bk_app_code=~\"$bk_app_code\", bk_domain=~\"$bk_domain\"}[30s]))"
            }
          ],
          "thresholds": [],
          "timeRegions": [],
          "title": "进程操作延迟/30s",
          "tooltip": {
            "shared": True,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "show": True,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:807",
              "format": "ms",
              "logBase": 1,
              "min": "0",
              "show": True
            },
            {
              "$$hashKey": "object:808",
              "format": "short",
              "logBase": 1,
              "show": True
            }
          ],
          "yaxis": {
            "align": False
          }
        }
      ],
      "title": "test_row",
      "type": "row"
    },
  ],
  "refresh": False,
  "schemaVersion": 39,
  "tags": [
    "cmdb"
  ],
  "templating": {
    "list": [
      {
        "allValue": "",
        "current": {
          "selected": False,
          "text": "process_name",
          "value": "process_name"
        },
        "hide": 0,
        "includeAll": False,
        "label": "show statistics group by",
        "multi": False,
        "name": "group",
        "options": [
          {
            "selected": True,
            "text": "process_name",
            "value": "process_name"
          },
          {
            "selected": False,
            "text": "instance",
            "value": "instance"
          },
          {
            "selected": False,
            "text": "process_instance",
            "value": "process_instance"
          }
        ],
        "query": "process_name,instance,process_instance",
        "queryValue": "",
        "refresh": 1,
        "skipUrlSync": False,
        "type": "custom"
      },
      {
        "current": {
          "selected": False,
          "text": "BCS-K8S-00000(蓝鲸7.0)",
          "value": "BCS-K8S-00000"
        },
        "datasource": {
          "type": "bkmonitor-timeseries-datasource",
          "uid": "000000002"
        },
        "definition": "- Blueking Monitor - 维度",
        "hide": 0,
        "includeAll": False,
        "multi": False,
        "name": "bk_cluster_id",
        "options": [],
        "query": {
          "metricConfig": {
            "data_source_label": "bk_monitor",
            "data_type_label": "time_series",
            "group_by": "bcs_cluster_id",
            "metric_field": "container_cpu_usage_seconds_total",
            "result_table_id": "",
            "result_table_label": "kubernetes",
            "where": []
          },
          "queryType": "dimension",
          "variables": ""
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": False,
        "sort": 0,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": False
      },
      {
        "current": {
          "selected": False,
          "text": "bk_cmdb",
          [...]

2024-12-10 06:52 UTC, unique0lai approved these changes

2024-12-10 06:52 UTC, merged