feat: 从指标数据源进行拓扑发现 --story=121070411
TencentBlueKing/bk-monitor pull request #4274
Opened 2024-12-08 13:00 UTC by rxwycdh

2024-12-09 04:15 UTC, ZhuoZhuoCrayon commented on bkmonitor/apm/task/tasks.py
> +        for i in ApmApplication.objects.filter(Q(is_enabled=True) & Q(is_enabled_metric=True)).values(
1. 感觉可以不用 Q：filter(is_enabled=True, is_enabled_metric=True)
2. 通常可以使用 `from django.db.models import Value` 来优化 bool 查询，因为 Django 在 xx=True/False 生成的查询语句是「真值判断」，会扫描所有的行，而 xx=1/0 只会扫描具体值为 `0` / `1` 的行，能有效避免慢查询。

![image](https://github.com/user-attachments/assets/ed93b47e-e745-40e5-b4c0-481e35f4c6f3)

2024-12-09 04:15 UTC, ZhuoZhuoCrayon commented on bkmonitor/apm/core/discover/metric/service.py
> +            topo_key = service_name or target
1. 目前线上只有一种情况会缺 target：OteamSDK 上报时，不指定 `service_name` 作为 attrs，但这种情况下，也不一定会有 `target`。
2. `target` 可能是 IP，可能是三段式 `platform.app.server`，可能是二段式 `app.server`。
3. 综上考虑，好像发现 `service_name` 即可，这样也不用考虑 `target` 的过滤和格式化问题。

2024-12-10 13:07 UTC, liuwenping requested changes

2024-12-10 13:07 UTC, liuwenping commented on bkmonitor/config/default.py
> +APM_APPLICATION_METRIC_DISCOVER_SPLIT_DELTA = 200
这个描述不对应

2024-12-11 03:24 UTC, liuwenping approved these changes

2024-12-11 03:24 UTC, merged