feat: 【告警】告警通知里，针对集群信息补充环境类型字段 --story=121108605
TencentBlueKing/bk-monitor pull request #4401
Opened 2024-12-13 09:16 UTC by tang202388

2024-12-13 09:19 UTC, tang202388 commented
自测截图：
修改后，关于集群的关联信息正常加上 环境类型了
![image](https://github.com/user-attachments/assets/0e5d0521-2bab-4d4a-8231-a0d15a79c6e1)

2024-12-29 14:51 UTC, chenguo367 requested changes

2024-12-29 14:51 UTC, chenguo367 commented on bkmonitor/packages/fta_web/alert/resources.py
> +                        environment_mapping[environment_types[bk_set_id]]
需要考虑cmdb迭代的问题。 新增了环境类型的时候， 此时我们写死123，则会有异常。这块如果没有对应翻译，就直接给到对应的类型id即可。

2024-12-30 08:07 UTC, tang202388 commented
自测截图补充：
当环境类型没有对应的翻译时，返回环境类型ID
![image](https://github.com/user-attachments/assets/c7d50431-2d2d-49bc-80fe-bee92ef9a310)

2025-04-17 02:34 UTC, merged