feat: 新增获取集群详情
TencentBlueKing/bk-monitor pull request #4404
Opened 2024-12-13 10:04 UTC by SevenDreamer

2024-12-13 10:10 UTC, SevenDreamer commented
- Feat: GetResourceDetail 新增获取集群的功能
![image](https://github.com/user-attachments/assets/ea2f2aa4-96ae-4820-a127-53cf4369021e)

- Fix: ListK8sResource查询报错
![Pasted image 20241213151810](https://github.com/user-attachments/assets/9a42bfa8-1b43-47c9-9397-8ec328c4b577)

2024-12-16 02:43 UTC, chenguo367 requested changes

2024-12-16 02:43 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/k8s/resources.py
> +        elif resource_type == "cluster":
如果什么都不做，看起来没有必要写这个分支

2024-12-16 06:54 UTC, chenguo367 approved these changes

2024-12-16 06:54 UTC, merged