fix: 在Profiling数据请求bkbase的位置，记录下请求参数，放到trace数据下
TencentBlueKing/bk-monitor pull request #4491
Opened 2024-12-19 09:10 UTC by WuFantaotao

2024-12-19 12:30 UTC, liuwenping requested changes

2024-12-19 12:30 UTC, liuwenping commented on bkmonitor/packages/apm_web/profile/doris/querier.py
> +                span.set_attributes(
这里只有一个需要设置，建议改为span.set_attribute，不带s的这个，然后传递key和val即可

2024-12-20 01:07 UTC, WuFantaotao commented on bkmonitor/packages/apm_web/profile/doris/querier.py
> +                span.set_attributes(
`span.set_attribute("request.body", json.dumps(params))`

2024-12-20 03:35 UTC, liuwenping approved these changes

2024-12-20 03:36 UTC, merged