【apm】 eBPF数据支持指标告警 --story=115368741
TencentBlueKing/bk-monitor pull request #456
Opened 2023-12-02 07:39 UTC by redyfang

2023-12-04 05:16 UTC, liuwenping requested changes

2023-12-04 05:16 UTC, liuwenping commented on bkmonitor/packages/apm_web/constants.py
> +APM_EBPF_METRIC_DEFAULT_NEGATIVE_PREFIX = "apm_ebpf_negative"
这个前缀有点长，需要讨论下

2023-12-04 05:16 UTC, liuwenping commented on bkmonitor/packages/apm_web/ebpf_handler.py
> +logger = logging.getLogger("ebpf.custom")
log的名字不要自定义一个新的出来，直接使用模块名即可

2023-12-04 05:16 UTC, liuwenping commented on bkmonitor/packages/apm_web/tasks.py
> +        CustomTimeSeriesInstall(bk_biz_id).create_default_custom_time_series()
这里没看到效验已经添加过的逻辑。
如果已经添加的话，是不是还会再调用一次

2023-12-04 05:16 UTC, liuwenping commented on bkmonitor/packages/apm_web/ebpf_handler.py
> +            "data_label": self.custom_report_name,
确认下，这个data_label是不是标签属性，如果是的话，可以打上APM、eBPF、flow_metrics等标签

2023-12-05 02:50 UTC, redyfang commented on bkmonitor/packages/apm_web/ebpf_handler.py
> +            "data_label": self.custom_report_name,
data_label 数据库 定义的是数据标签，但是自定义指标创建过程中，data_label --> 英文名称。故不可以改。
name 也可以改，需要添加效验已经添加过逻辑，这个需要用name字段做判断，使用一堆标签会导致判断失效

2023-12-05 02:51 UTC, redyfang commented on bkmonitor/packages/apm_web/ebpf_handler.py
> +            "data_label": self.custom_report_name,
data_label 数据库 定义的是数据标签，但是自定义指标创建过程中，data_label --> 英文名称。故不可以改。
name 也不可以改，需要添加【效验已经添加过逻辑】，这个需要用name字段做判断，使用一堆标签会导致判断失效

2026-01-14 03:40 UTC, closed without merging