fix: 修复 nginx 代理路径和平台路径不一致会导致的问题
TencentBlueKing/bk-monitor pull request #629
Opened 2023-12-14 09:37 UTC by wangtuchuan

2023-12-15 09:20 UTC, unique0lai requested changes

2023-12-15 09:20 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +            request.META.get("HTTP_X_ORIGINAL_URI") if request.META.get("HTTP_X_ORIGINAL_URI") else request.path
这里可以写成request.META.get("HTTP_X_ORIGINAL_URI") or request.path

2023-12-15 09:20 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
>              and request.get_host() == weixin_settings.WEIXIN_APP_EXTERNAL_HOST
这里直接用X_FORWARDED_WEIXIN_HOST的值判断吧，否则还需要额外进行配置

2023-12-15 09:20 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +        if settings.X_FORWARDED_WEIXIN_HOST in request.META:
这里使用weixin_settings吧，和下面保持统一

2023-12-15 09:20 UTC, unique0lai commented on bkmonitor/packages/weixin/core/settings.py
> +WEIXIN_SITE_URL = os.environ.get("BKAPP_WEIXIN_SITE_URL", SITE_URL + "weixin/")
这里拿不到SITE_URL会报错的，改成默认值就好了

2023-12-15 09:40 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/accounts.py
> +            request.META.get("HTTP_X_ORIGINAL_URI") if request.META.get("HTTP_X_ORIGINAL_URI") else request.path
已按照 review 意见修改

2023-12-27 08:23 UTC, unique0lai requested changes

2023-12-27 08:23 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +            "openid": base_data.get("userid"),
这个字段了解么？这个userid是不是企业微信下的概念？如果是微信是不是应该继续使用openid？

2023-12-27 08:23 UTC, unique0lai commented on bkmonitor/packages/weixin/core/api.py
> +    QY_WEIXIN_GET_ACCESS_TOKEN_URL = weixin_settings.WEIXIN_QY_DOMAIN + '/cgi-bin/gettoken'
这些路径拼接可以都改为使用urljoin处理

2023-12-27 08:23 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +    WEIXIN_OAUTH_URL = weixin_settings.WEIXIN_APP_URL_PREFIX + "/connect/oauth2/authorize"
这些路径拼接可以都改为使用urljoin处理

2023-12-27 08:23 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +        if request.get_full_path().startswith(settings.SITE_URL):
这里的判断是否应该改为replace的第一个参数，否则在容器化环境下，SITE_URL为`/`，这个逻辑几乎必然触发。
另外，当WEIXIN_SITE_URL没有被特殊修改的情况下，其实也没有必要执行replace。

2023-12-27 08:23 UTC, unique0lai commented on bkmonitor/packages/weixin/core/accounts.py
> +        # query = "c_url={}".format(request.get_full_path())
这个注释可以去掉

2023-12-27 09:11 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/accounts.py
> +            "openid": base_data.get("userid"),
已按照评审意见进行修改

2023-12-27 09:11 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/api.py
> +    QY_WEIXIN_GET_ACCESS_TOKEN_URL = weixin_settings.WEIXIN_QY_DOMAIN + '/cgi-bin/gettoken'
已按照评审意见进行修改

2023-12-27 09:11 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/accounts.py
> +    WEIXIN_OAUTH_URL = weixin_settings.WEIXIN_APP_URL_PREFIX + "/connect/oauth2/authorize"
已按照评审意见进行修改

2023-12-27 09:11 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/accounts.py
> +        if request.get_full_path().startswith(settings.SITE_URL):
已按照评审意见进行修改

2023-12-27 09:11 UTC, wangtuchuan commented on bkmonitor/packages/weixin/core/accounts.py
> +        # query = "c_url={}".format(request.get_full_path())
已按照评审意见进行修改

2024-01-02 03:50 UTC, unique0lai approved these changes

2024-01-02 03:50 UTC, merged