Feat: 尾部采样 #1010158081115216418
TencentBlueKing/bk-monitor pull request #682
Opened 2023-12-19 12:23 UTC by rxwycdh

2023-12-26 10:21 UTC, liuwenping requested changes

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +    def _is_diff(cls, a, b, exclude_fields=None):
这个is_diff的判断。如果exclude_fields有值的话，会改变a、b原本的值，这个设计不合理，至少从名字上看不出来，会成为后面的隐藏BUG

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        return json.dumps(a, sort_keys=True) != json.dumps(b, sort_keys=True)
这个json.dumps方法来判断是否有差异，也会有误判的情况。 可以考虑代码中的count_md5方法

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +class _Logger:
这个的取名建议更改一下，和原本的Python日志记录logger区分开来，避免后面的人混用这个

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +            "data_scenario": "queue",
这个接入类型，之前讨论是要一种新的接入方式，这里看还是没有变化

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        BkdataFlowConfig.objects.filter(id=self.flow.id).update(**{field_name: field_value})
这样子更新，效率有点低，需要优化一下。一个字段变更就两次sql查询设置

2023-12-26 10:21 UTC, liuwenping commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        for i in range(10):
这个重试次数10，建议做成配置项

2023-12-27 10:49 UTC, rxwycdh commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        return json.dumps(a, sort_keys=True) != json.dumps(b, sort_keys=True)
已调整

2023-12-27 10:51 UTC, rxwycdh commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +class _Logger:
-> _BkdataFlowLogger

2023-12-27 10:58 UTC, rxwycdh commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        for i in range(10):
已调整

2023-12-27 11:09 UTC, rxwycdh commented on bkmonitor/apm/core/handlers/bk_data/flow.py
> +        BkdataFlowConfig.objects.filter(id=self.flow.id).update(**{field_name: field_value})
改成了：
        BkdataFlowConfig.objects.filter(id=self.flow.id).update(**{field_name: field_value})
        self.flow.refresh_from_db()
 这块没想到更好的方法，

2023-12-28 08:02 UTC, liuwenping requested changes

2023-12-28 08:02 UTC, liuwenping commented on bkmonitor/bkmonitor/dataflow/task/apm_tail_sampling.py
> +import com.google.gson.Gson;
这段代码，base64一下，然后传递过去的时候，再解码

2023-12-29 03:58 UTC, liuwenping approved these changes

2023-12-29 04:07 UTC, liuwenping approved these changes

2023-12-29 04:08 UTC, merged