feat: 策略缓存执行逻辑优化，提升时效性 --story=115173113
TencentBlueKing/bk-monitor pull request #749
Opened 2023-12-23 09:17 UTC by chenguo367

2023-12-23 09:18 UTC, chenguo367 commented
#### 背景：
- 当前每分钟全量进行策略缓存刷新，耗时过大，导致策略修改后生效时间较长
#### 目标：
1. 每个常规周期，仅增量更新近一段时间内变更过策略的业务  （每分钟）
2. 每个固定周期（较大）全业务更新全量策略（每小时）
> 基于目标1， 要求可以基于`业务维度`执行策略缓存的所有逻辑。

#### 当前策略缓存执行流程

```

入口：refresh()

获取目标策略列表并统计策略有效性： get_strategies  -> strategies

处理器处理目标策略： strategies：

# 添加监控目标抑制条件
cls.add_target_shield_condition,  
# 针对k8s策略添加启用集群范围生效条件
cls.add_enabled_cluster_condition,  


# 刷新策略ID列表缓存【全业务】-> 需要重新适配
cls.refresh_strategy_ids,  
# 刷新配置了策略的业务ID列表【全业务】 -> 重新适配
cls.refresh_bk_biz_ids,  
# 刷新策略缓存【全业务】清理删除的key -> 重新适配
cls.refresh_strategy,  


# 刷新实时数据的相关策略【全业务】 -> 增量刷新，不处理
cls.refresh_real_time_strategy_ids,  
# 刷新gse事件策略ID列表缓存【全业务】 -> 增量刷新，不处理
cls.refresh_gse_alarm_strategy_ids, 
# 刷新自愈策略列表缓存【全业务】 -> 增量刷新，不处理
cls.refresh_fta_alert_strategy_ids,  

# 更新策略分组周期【全业务】 -> 看起来没有用了，清理掉
cls.refresh_strategy_group_interval,
```



```python
# 策略缓存刷新规则：  
# 1. 每个常规周期，仅增量更新近一段时间内变更过策略的业务  
# 2. 每个固定周期（较大）全业务更新全量策略
```

2023-12-23 09:18 UTC, chenguo367 commented
#### 背景：
- 当前每分钟全量进行策略缓存刷新，耗时过大，导致策略修改后生效时间较长
#### 目标：
1. 每个常规周期，仅增量更新近一段时间内变更过策略的业务  （每分钟）
2. 每个固定周期（较大）全业务更新全量策略（每小时）
> 基于目标1， 要求可以基于`业务维度`执行策略缓存的所有逻辑。

#### 当前策略缓存执行流程

```

入口：refresh()

获取目标策略列表并统计策略有效性： get_strategies  -> strategies

处理器处理目标策略： strategies：

# 添加监控目标抑制条件
cls.add_target_shield_condition,  
# 针对k8s策略添加启用集群范围生效条件
cls.add_enabled_cluster_condition,  


# 刷新策略ID列表缓存【全业务】-> 需要重新适配
cls.refresh_strategy_ids,  
# 刷新配置了策略的业务ID列表【全业务】 -> 重新适配
cls.refresh_bk_biz_ids,  
# 刷新策略缓存【全业务】清理删除的key -> 重新适配
cls.refresh_strategy,  


# 刷新实时数据的相关策略【全业务】 -> 增量刷新，不处理
cls.refresh_real_time_strategy_ids,  
# 刷新gse事件策略ID列表缓存【全业务】 -> 增量刷新，不处理
cls.refresh_gse_alarm_strategy_ids, 
# 刷新自愈策略列表缓存【全业务】 -> 增量刷新，不处理
cls.refresh_fta_alert_strategy_ids,  

# 更新策略分组周期【全业务】 -> 看起来没有用了，清理掉
cls.refresh_strategy_group_interval,
```



```python
# 策略缓存刷新规则：  
# 1. 每个常规周期，仅增量更新近一段时间内变更过策略的业务  
# 2. 每个固定周期（较大）全业务更新全量策略
```

2023-12-25 03:34 UTC, unique0lai requested changes

2023-12-25 03:34 UTC, unique0lai commented on bkmonitor/alarm_backends/core/cache/strategy.py
> +        histories = StrategyHistoryModel.objects.filter(create_time__gt=datetime.now() - timedelta(seconds=timeshift))
create_time需要加个索引，目前的量不小了

2023-12-25 03:34 UTC, unique0lai commented on bkmonitor/alarm_backends/core/cache/strategy.py
>          cls.cache.set(cls.IDS_CACHE_KEY, json.dumps(new_strategy_ids), cls.CACHE_TIMEOUT)
策略ID列表在部分刷新时会受到影响

2023-12-25 03:34 UTC, unique0lai commented on bkmonitor/alarm_backends/core/cache/strategy.py
> +            refresh_strategy,
real_time_data_strategy_ids等缓存未处理，需要考虑产生的数据不一致问题

2023-12-25 06:59 UTC, unique0lai approved these changes

2023-12-25 09:31 UTC, merged