feat: 运营指标 get_ts_data 改造为 unify_query --story=115721504
TencentBlueKing/bk-monitor pull request #846
Opened 2023-12-29 08:16 UTC by lthon-sha

2024-01-02 07:25 UTC, chenguo367 requested changes

2024-01-02 07:25 UTC, chenguo367 commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +        bk_biz_id: Optional[Union[int, str]] = None,
这里入参的顺序变更，需要评估影响范围的。所有调用的地方都会收到影响。不要轻易的变更函数的参数顺序。 而且从需求看，bk_biz_id为None也是可以在不改变顺序的情况下传参进来的。

2024-01-02 07:35 UTC, chenguo367 requested changes

2024-01-02 07:35 UTC, chenguo367 commented on bkmonitor/bkm_space/utils.py
> +def bk_biz_id_to_space_uid(bk_biz_id: Optional[Union[str, int]]) -> str:
这里函数设计就是业务id转空间唯一标识，  参数支持不传bk_biz_id 不符合函数设计。

2024-01-08 10:11 UTC, lthon-sha commented on bkmonitor/packages/monitor_web/overview/tools.py
> +        )
这里有点不太确定，用了 promql，不知道是否有更方便的接口
实际是想用即时查询的，所以时间范围和步长就配置成只查一次，不知道是否有相应接口。

2024-01-22 06:57 UTC, chenguo367 requested changes

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/alarm_backends/management/story/kernel_story.py
> +                start_time=now_ts.replace(minutes=-1).timestamp * 1000, end_time=now_ts.timestamp * 1000
这里start_time 看起来是一分钟前，改造前的逻辑是最近10分钟，保持一致

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/alarm_backends/management/story/kernel_story.py
>      warning_duration = 2
之前2s的逻辑是判定api的请求堵塞（api调用总耗时 - 实际耗时）。现在用来判定查询耗时的话，调整大一点。warning_duration设置为10s。

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +        bk_biz_id: Optional[Union[int, str]],
int or None

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> -    def space_uid(self):
这里cached_property属性保留，如果是None的话，space_uid 也返回None

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/api/unify_query/default.py
> +        space_uid = serializers.CharField(required=False)
约定全局查询时， space_uid 为None。
加一个： all_null = True

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/bkmonitor/data_source/unify_query/query.py
> +        if self.bk_biz_id is None:
全局查询时，space_uid也传下去，值用None

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/overview/tools.py
> +            start_time=now_ts.replace(minutes=-1).timestamp * 1000, end_time=now_ts.timestamp * 1000
start_time 和改造前保持一致，使用5min（最近5分钟）

2024-01-22 06:57 UTC, chenguo367 commented on bkmonitor/packages/monitor_web/overview/tools.py
> +        )
这里是判断是否有数据，使用的查询为，查询近5分钟system:cpu_summary:usage指标的总个数，如果不为0则表示有数据。这里时间范围是5min， 聚合周期也是5min。 数据在查询的时候做了聚合。 这里适配也按这个思路写聚合promql即可。避免即时进行原始数据查询，未经聚合的数据量级较大，没必要浪费传输时间。

2024-01-22 09:37 UTC, chenguo367 approved these changes

2024-01-22 09:39 UTC, chenguo367 approved these changes

2024-01-22 09:40 UTC, merged