feat: [apm] add profile interface
TencentBlueKing/bk-monitor pull request #900
Opened 2024-01-05 07:19 UTC by redyfang

2024-01-05 08:47 UTC, IMBlues requested changes

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/tasks.py
> +def profile_file_upload_and_parse(fh, file_type, profile_id, bk_biz_id, app_name):
参数可以加上类型注解会更好一些

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    return "Profile-" + now_str + ".pprof"
写成一个常量模版更好？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/serializers.py
> +class ProfileListFileSerializer(serializers.Serializer):
这里还需要 service_name 作为参数

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +def generate_svg_data(data: dict):
这个函数看起来更适合放到 `diagrams/callgraph.py` 里，可以给 `draw()` 方法协议增加一种「模式」选择：纯数据模式 或 图片模式，目前仅在 `callgraph` 默认使用图片模式。

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +            from apm_web.profile.file_handler import ProfilingFileHandler
这里为什么要异步引用呢？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/models/profile.py
> +    status = models.CharField("状态", max_length=36, default="")
这里定义一个 `Enum` `UploadedFileStatus`，然后这里加一个 choices 参数吧

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +            status=_("已上传"),
这里用 Enum 存英文短字符串或者数字，由 `ProfileUploadRecordSLZ` 在返回时将值转换成可读的中文吧

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    def list_profile_upload_record(self, request: Request):
Nit: list_profile_upload_records

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        if validated_data.get("origin_file_name"):
还有 service_name 需要过滤

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        return Response(data=data)
`ProfileUploadRecordSLZ(queryset, many=True)` 会不会更简单一点？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    def call_graph(cls, validated_data, base_param: dict):
就像上面提到的，我们把 `call_graph`/`table`/`flamegraph` 视为同级，仅通过前端传递的参数返回不同的数据结构而已，这里我们可以把 `call_graph` 的 svg 图片也视为一种特殊的数据，直接在通用数据查询 API 里处理就好了，不需要额外新增 API

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        from io import BytesIO
直接放到文件顶部引用，不然每次调用 API 时都需要 import 一次，[Python import 通常来说是比较慢的](https://gregoryszorc.com/blog/2019/01/10/what-i've-learned-about-optimizing-python/)，尽量少的在函数里引用

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    def get_profile_data(cls, validated_data, base_param: dict) -> DorisConverter:
Nit: 这个抽成通用的方法挺好的，不过既然是方法了，感觉可以把过滤参数直接平铺出来，下面直接引用感觉会更清晰一点？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        if (
这里只判断一个变量 `is_compared` 会不会更简单一点？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +            return Response(data={k: v for diagram_dict in diff_diagram_dicts for k, v in diagram_dict.items()})
这下面的数据判断有些混乱，这里实际上有两个主要的分支：
- `is_compared` 为 `false`，直接进入数据绘图 `draw()`
- `is_compared` 为 `true`，获取到对比数据后，进入对比绘图 `diff()`

同时 diagram_types 是一个列表，通过遍历其中的元素，获取每一个 types 的数据，直接返回。

其中有一个特殊的 `call_graph` 类型调用 `draw()` 直接返回 svg 图片的情况，这时候可以加一个返回值 `return_file_data` 作为标志位，当这个标志为真，Response 里的 mime_type 改成图片，反之直接返回数据即可。

看下这个梳理会不会更清晰一点？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/webpack/src/monitor-api/modules/apm_profile.js
> +export const listProfileUploadRecord = request('GET', 'apm/profile_api/profiling/list_profile_upload_record/');
Nit：按照 Restful 的风格，`apm/profile_api/profiling/upload_records` 感觉会更简洁一点，当然只是一种风格偏好，仅供参考

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +            uploaded,
这里有测试过么？直接把 `uploaded` 当作参数传给 celery 貌似不太行，就算是能传感觉效率也很低，这里的 uploaded 很可能上百兆。上面我看已经在上传到 bk_repo ，这里理论上只需要获取到一个文件 Key 就可以了。

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +            logger.error(f"{uploaded.name} file upload to bkrepo failed, error: {e}")
如果上传失败，下面的 `UploadRecord` 应该需要记录上传失败的错误，对应的 task 也不应该再执行了

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    from graphviz import Digraph
同样的，放到顶层引用，非必要不做函数引用

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +    now_str = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
使用 Django 提供的 `timezone.now()`

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/pprof/converter.py
> +        except Exception:
可能要加上

```python
 # pylint: disable=broad-except
```

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/serializers.py
> +    diagram_type = serializers.ListSerializer(
`diagram_types`

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/diagrams/callgraph.py
> +    @classmethod
这个函数还有下面的 diff 函数，为什么要写成 `classmethod` ？

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/diagrams/callgraph.py
> +        return {
call_graph 目前不存在对比的需求，可以直接 `raise NotImplementedError` 调用侧捕捉异常并返回给前端就可以

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/diagrams/table.py
> +        # todo 后续肯能展示字段按需调整
对比这块儿，我更建议先暂时按下，因为更加通用的做法是，我们在拿到两份数据后，对数据建立一棵抽象的对比树 （类似 trace 的 DiffTree），再通过 DiffTree 来转换成不同的图表，这样能保证不同的图表之间的对比逻辑是一致的，也方便在后面针对“对比”逻辑进行雕琢

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/file_handler.py
> +            queryset.update(status=_("解析失败"))
同其他地方提到的，用 `Enum` 来处理，而不是 `Magic string`

2024-01-05 08:47 UTC, IMBlues commented on bkmonitor/packages/apm_web/models/profile.py
> +    file_name = models.CharField("新文件名称", max_length=255, default="")
新文件名如果是确定格式的，长度可以做一个限制，255 略长

2024-01-08 02:33 UTC, redyfang commented on bkmonitor/packages/apm_web/profile/views.py
> +    return "Profile-" + now_str + ".pprof"
OK

2024-01-08 02:33 UTC, redyfang commented on bkmonitor/packages/apm_web/profile/serializers.py
> +class ProfileListFileSerializer(serializers.Serializer):
已加

2024-01-08 02:35 UTC, redyfang commented on bkmonitor/packages/apm_web/profile/views.py
> +    def get_profile_data(cls, validated_data, base_param: dict) -> DorisConverter:
确实会更清晰一些

2024-01-08 10:48 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/constants.py
> +class UploadedFileStatus:
可以参考一下 Django 提供的方案

https://stackoverflow.com/questions/54802616/how-can-one-use-enums-as-a-choice-field-in-a-django-model

2024-01-08 10:48 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        ProfilingFileHandler().bk_repo_storage.client.upload_fileobj(uploaded, key=uploaded.name)
这里的异常是否包裹一下会更好？

```python
try:
    ProfilingFileHandler().bk_repo_storage.client.upload_fileobj(uploaded, key=uploaded.name)
except Exception:
    logger.exception("failed to upload file to bkrepo")
    raise Exception(_("上传文件失败"))
```

2024-01-08 10:48 UTC, IMBlues commented on bkmonitor/packages/apm_web/profile/views.py
> +        from apm_web.tasks import profile_file_upload_and_parse
这里一定要函数 import 吗？

2024-01-08 10:48 UTC, IMBlues commented on bkmonitor/packages/apm_web/tasks.py
> +    from apm_web.profile.file_handler import ProfilingFileHandler
同上，是否可以通过调整文件的目录架构来减少函数 import ？

2024-01-09 03:09 UTC, IMBlues commented on bkmonitor/packages/apm_web/models/profile.py
> +        "状态", max_length=36, choices=UploadedFileStatus.choices, default=UploadedFileStatus.UNKNOWN
这个默认状态写成【未知】感觉有点点奇怪，我们能否在流程上保证在确保文件已经上传后，再创建 DB 记录？这样默认状态就是已上传，我们只需要关注解析的结果即可

2024-01-09 03:23 UTC, IMBlues approved these changes

2024-01-09 03:25 UTC, merged